BUILD_DIR ?= build
CMAKE ?= cmake
AUREX_PERF_THRESHOLD_PROFILE ?= local
AUREX_PERF_THRESHOLD_SCALE ?= 1.0
AUREX_GENERIC_STRESS_COUNTS ?= 100,200
AUREX_GENERIC_STRESS_SHAPE ?= mixed
AUREX_GENERIC_STRESS_MAX_RSS_MIB ?= 512
AUREX_GENERIC_STRESS_MAX_ELAPSED_MS ?= 30000
AUREX_AST_STRESS_COUNTS ?= 1000,5000
AUREX_AST_STRESS_SHAPE ?= mixed
AUREX_AST_STRESS_MAX_RSS_MIB ?= 512
AUREX_AST_STRESS_MAX_ELAPSED_MS ?= 30000
AUREX_DIAGNOSTIC_STRESS_COUNTS ?= 100,500
AUREX_DIAGNOSTIC_STRESS_SHAPE ?= mixed
AUREX_DIAGNOSTIC_STRESS_MAX_RSS_MIB ?= 512
AUREX_DIAGNOSTIC_STRESS_MAX_ELAPSED_MS ?= 30000
AUREX_RELEASE_GENERIC_STRESS_COUNTS ?= 5000
AUREX_RELEASE_GENERIC_STRESS_SHAPE ?= mixed
AUREX_RELEASE_GENERIC_STRESS_MAX_RSS_MIB ?= 512
AUREX_RELEASE_GENERIC_STRESS_MAX_ELAPSED_MS ?= 120000
AUREX_RELEASE_AST_STRESS_COUNTS ?= 2000000
AUREX_RELEASE_AST_STRESS_SHAPE ?= mixed
AUREX_RELEASE_AST_STRESS_MAX_RSS_MIB ?= 2048
AUREX_RELEASE_AST_STRESS_MAX_ELAPSED_MS ?= 180000
AUREX_RELEASE_DIAGNOSTIC_STRESS_COUNTS ?= 5000
AUREX_RELEASE_DIAGNOSTIC_STRESS_SHAPE ?= mixed
AUREX_RELEASE_DIAGNOSTIC_STRESS_MAX_RSS_MIB ?= 512
AUREX_RELEASE_DIAGNOSTIC_STRESS_MAX_ELAPSED_MS ?= 120000
AUREX_RELEASE_LTO_BUILD_DIR ?= build-perf-lto
PERF_THRESHOLD_ENV = AUREX_PERF_THRESHOLD_PROFILE=$(AUREX_PERF_THRESHOLD_PROFILE) AUREX_PERF_THRESHOLD_SCALE=$(AUREX_PERF_THRESHOLD_SCALE)

all: build

configure:
	$(CMAKE) -S . -B $(BUILD_DIR)

build: configure
	$(CMAKE) --build $(BUILD_DIR) -j

test:
	tools/run_tests.sh

bench:
	tools/bench.py

perf:
	tools/perf_report.py
	tools/frontend_compare.py

perf-stress:
	tools/generic_stress.py
	tools/ast_stress.py
	tools/diagnostic_stress.py --skip-build

perf-stress-threshold:
	$(PERF_THRESHOLD_ENV) AUREX_GENERIC_STRESS_COUNTS=$(AUREX_GENERIC_STRESS_COUNTS) AUREX_GENERIC_STRESS_SHAPE=$(AUREX_GENERIC_STRESS_SHAPE) AUREX_GENERIC_STRESS_MAX_RSS_MIB=$(AUREX_GENERIC_STRESS_MAX_RSS_MIB) AUREX_GENERIC_STRESS_MAX_ELAPSED_MS=$(AUREX_GENERIC_STRESS_MAX_ELAPSED_MS) tools/generic_stress.py
	$(PERF_THRESHOLD_ENV) AUREX_AST_STRESS_COUNTS=$(AUREX_AST_STRESS_COUNTS) AUREX_AST_STRESS_SHAPE=$(AUREX_AST_STRESS_SHAPE) AUREX_AST_STRESS_MAX_RSS_MIB=$(AUREX_AST_STRESS_MAX_RSS_MIB) AUREX_AST_STRESS_MAX_ELAPSED_MS=$(AUREX_AST_STRESS_MAX_ELAPSED_MS) tools/ast_stress.py --skip-build
	$(PERF_THRESHOLD_ENV) AUREX_DIAGNOSTIC_STRESS_COUNTS=$(AUREX_DIAGNOSTIC_STRESS_COUNTS) AUREX_DIAGNOSTIC_STRESS_SHAPE=$(AUREX_DIAGNOSTIC_STRESS_SHAPE) AUREX_DIAGNOSTIC_STRESS_MAX_RSS_MIB=$(AUREX_DIAGNOSTIC_STRESS_MAX_RSS_MIB) AUREX_DIAGNOSTIC_STRESS_MAX_ELAPSED_MS=$(AUREX_DIAGNOSTIC_STRESS_MAX_ELAPSED_MS) tools/diagnostic_stress.py --skip-build

perf-release-threshold:
	$(PERF_THRESHOLD_ENV) AUREX_GENERIC_STRESS_COUNTS=$(AUREX_RELEASE_GENERIC_STRESS_COUNTS) AUREX_GENERIC_STRESS_SHAPE=$(AUREX_RELEASE_GENERIC_STRESS_SHAPE) AUREX_GENERIC_STRESS_MAX_RSS_MIB=$(AUREX_RELEASE_GENERIC_STRESS_MAX_RSS_MIB) AUREX_GENERIC_STRESS_MAX_ELAPSED_MS=$(AUREX_RELEASE_GENERIC_STRESS_MAX_ELAPSED_MS) tools/generic_stress.py
	$(PERF_THRESHOLD_ENV) AUREX_AST_STRESS_COUNTS=$(AUREX_RELEASE_AST_STRESS_COUNTS) AUREX_AST_STRESS_SHAPE=$(AUREX_RELEASE_AST_STRESS_SHAPE) AUREX_AST_STRESS_MAX_RSS_MIB=$(AUREX_RELEASE_AST_STRESS_MAX_RSS_MIB) AUREX_AST_STRESS_MAX_ELAPSED_MS=$(AUREX_RELEASE_AST_STRESS_MAX_ELAPSED_MS) tools/ast_stress.py --skip-build
	$(PERF_THRESHOLD_ENV) AUREX_DIAGNOSTIC_STRESS_COUNTS=$(AUREX_RELEASE_DIAGNOSTIC_STRESS_COUNTS) AUREX_DIAGNOSTIC_STRESS_SHAPE=$(AUREX_RELEASE_DIAGNOSTIC_STRESS_SHAPE) AUREX_DIAGNOSTIC_STRESS_MAX_RSS_MIB=$(AUREX_RELEASE_DIAGNOSTIC_STRESS_MAX_RSS_MIB) AUREX_DIAGNOSTIC_STRESS_MAX_ELAPSED_MS=$(AUREX_RELEASE_DIAGNOSTIC_STRESS_MAX_ELAPSED_MS) tools/diagnostic_stress.py --skip-build

perf-release-lto-threshold:
	$(PERF_THRESHOLD_ENV) AUREX_STRESS_BUILD_DIR=$(AUREX_RELEASE_LTO_BUILD_DIR) AUREX_STRESS_ENABLE_LTO=ON AUREX_GENERIC_STRESS_COUNTS=$(AUREX_RELEASE_GENERIC_STRESS_COUNTS) AUREX_GENERIC_STRESS_SHAPE=$(AUREX_RELEASE_GENERIC_STRESS_SHAPE) AUREX_GENERIC_STRESS_MAX_RSS_MIB=$(AUREX_RELEASE_GENERIC_STRESS_MAX_RSS_MIB) AUREX_GENERIC_STRESS_MAX_ELAPSED_MS=$(AUREX_RELEASE_GENERIC_STRESS_MAX_ELAPSED_MS) tools/generic_stress.py
	$(PERF_THRESHOLD_ENV) AUREX_STRESS_BUILD_DIR=$(AUREX_RELEASE_LTO_BUILD_DIR) AUREX_STRESS_ENABLE_LTO=ON AUREX_AST_STRESS_COUNTS=$(AUREX_RELEASE_AST_STRESS_COUNTS) AUREX_AST_STRESS_SHAPE=$(AUREX_RELEASE_AST_STRESS_SHAPE) AUREX_AST_STRESS_MAX_RSS_MIB=$(AUREX_RELEASE_AST_STRESS_MAX_RSS_MIB) AUREX_AST_STRESS_MAX_ELAPSED_MS=$(AUREX_RELEASE_AST_STRESS_MAX_ELAPSED_MS) tools/ast_stress.py --skip-build
	$(PERF_THRESHOLD_ENV) AUREX_STRESS_BUILD_DIR=$(AUREX_RELEASE_LTO_BUILD_DIR) AUREX_STRESS_ENABLE_LTO=ON AUREX_DIAGNOSTIC_STRESS_COUNTS=$(AUREX_RELEASE_DIAGNOSTIC_STRESS_COUNTS) AUREX_DIAGNOSTIC_STRESS_SHAPE=$(AUREX_RELEASE_DIAGNOSTIC_STRESS_SHAPE) AUREX_DIAGNOSTIC_STRESS_MAX_RSS_MIB=$(AUREX_RELEASE_DIAGNOSTIC_STRESS_MAX_RSS_MIB) AUREX_DIAGNOSTIC_STRESS_MAX_ELAPSED_MS=$(AUREX_RELEASE_DIAGNOSTIC_STRESS_MAX_ELAPSED_MS) tools/diagnostic_stress.py --skip-build

perf-release-all-threshold: perf-release-threshold perf-release-lto-threshold

perf-ast-stress:
	tools/ast_stress.py

perf-compare:
	tools/frontend_compare.py

clean:
	$(CMAKE) --build $(BUILD_DIR) --target clean || true

.PHONY: all configure build test bench perf perf-stress perf-stress-threshold perf-release-threshold perf-release-lto-threshold perf-release-all-threshold perf-ast-stress perf-compare clean
