BUILD_ROOT ?= build
BUILD_DIR ?= $(BUILD_ROOT)/full-llvm
CMAKE ?= cmake
AUREX_PERF_THRESHOLD_PROFILE ?= local
AUREX_PERF_THRESHOLD_SCALE ?= 1.0
AUREX_GENERIC_STRESS_COUNTS ?= 100,200
AUREX_GENERIC_STRESS_SHAPE ?= mixed
AUREX_GENERIC_STRESS_MAX_RSS_MIB ?= 512
AUREX_GENERIC_STRESS_MAX_ELAPSED_MS ?= 30000
AUREX_AST_STRESS_COUNTS ?= 1000,5000
AUREX_AST_STRESS_SHAPE ?= mixed
AUREX_AST_STRESS_MAX_RSS_MIB ?= 512
AUREX_AST_STRESS_MAX_ELAPSED_MS ?= 30000
AUREX_DIAGNOSTIC_STRESS_COUNTS ?= 100,500
AUREX_DIAGNOSTIC_STRESS_SHAPE ?= mixed
AUREX_DIAGNOSTIC_STRESS_MAX_RSS_MIB ?= 512
AUREX_DIAGNOSTIC_STRESS_MAX_ELAPSED_MS ?= 30000
AUREX_QUERY_PRUNING_GATE_FUNCTIONS ?= 32
AUREX_QUERY_GRAPH_FUZZ_ROUNDS ?= 4
AUREX_QUERY_GRAPH_FUZZ_FUNCTIONS ?= 8
AUREX_QUERY_GRAPH_FUZZ_FUNCTION_STEP ?= 8
AUREX_QUERY_GRAPH_FUZZ_BUILD_DIR ?= $(BUILD_ROOT)/perf
AUREX_SANITIZER_BUILD_DIR ?= $(BUILD_ROOT)/sanitize
AUREX_RELEASE_GENERIC_STRESS_COUNTS ?= 5000
AUREX_RELEASE_GENERIC_STRESS_SHAPE ?= mixed
AUREX_RELEASE_GENERIC_STRESS_MAX_RSS_MIB ?= 640
AUREX_RELEASE_GENERIC_STRESS_MAX_ELAPSED_MS ?= 120000
AUREX_RELEASE_AST_STRESS_COUNTS ?= 2000000
AUREX_RELEASE_AST_STRESS_SHAPE ?= mixed
AUREX_RELEASE_AST_STRESS_MAX_RSS_MIB ?= 8192
AUREX_RELEASE_AST_STRESS_MAX_ELAPSED_MS ?= 180000
AUREX_RELEASE_DIAGNOSTIC_STRESS_COUNTS ?= 5000
AUREX_RELEASE_DIAGNOSTIC_STRESS_SHAPE ?= mixed
AUREX_RELEASE_DIAGNOSTIC_STRESS_MAX_RSS_MIB ?= 512
AUREX_RELEASE_DIAGNOSTIC_STRESS_MAX_ELAPSED_MS ?= 120000
AUREX_RELEASE_LTO_BUILD_DIR ?= $(BUILD_ROOT)/perf-lto
AUREX_RELEASE_BUILD_DIR ?= $(AUREX_RELEASE_LTO_BUILD_DIR)
PERF_THRESHOLD_ENV = AUREX_PERF_THRESHOLD_PROFILE=$(AUREX_PERF_THRESHOLD_PROFILE) AUREX_PERF_THRESHOLD_SCALE=$(AUREX_PERF_THRESHOLD_SCALE)

all: build

configure:
	$(CMAKE) -S . -B $(BUILD_DIR)

build: configure
	$(CMAKE) --build $(BUILD_DIR) -j

test:
	tools/run_tests.sh

format-check:
	tools/format_check.py --base HEAD

bench:
	tools/bench.py

perf:
	tools/perf_report.py
	tools/frontend_compare.py

perf-stress:
	tools/generic_stress.py
	tools/ast_stress.py
	tools/diagnostic_stress.py --skip-build
	tools/query_pruning_gate.py --skip-build
	AUREX_QUERY_GRAPH_FUZZ_BUILD_DIR=$(AUREX_QUERY_GRAPH_FUZZ_BUILD_DIR) tools/query_graph_fuzz.py --skip-build --rounds $(AUREX_QUERY_GRAPH_FUZZ_ROUNDS) --functions $(AUREX_QUERY_GRAPH_FUZZ_FUNCTIONS) --function-step $(AUREX_QUERY_GRAPH_FUZZ_FUNCTION_STEP)

perf-stress-threshold:
	$(PERF_THRESHOLD_ENV) AUREX_GENERIC_STRESS_COUNTS=$(AUREX_GENERIC_STRESS_COUNTS) AUREX_GENERIC_STRESS_SHAPE=$(AUREX_GENERIC_STRESS_SHAPE) AUREX_GENERIC_STRESS_MAX_RSS_MIB=$(AUREX_GENERIC_STRESS_MAX_RSS_MIB) AUREX_GENERIC_STRESS_MAX_ELAPSED_MS=$(AUREX_GENERIC_STRESS_MAX_ELAPSED_MS) tools/generic_stress.py
	$(PERF_THRESHOLD_ENV) AUREX_AST_STRESS_COUNTS=$(AUREX_AST_STRESS_COUNTS) AUREX_AST_STRESS_SHAPE=$(AUREX_AST_STRESS_SHAPE) AUREX_AST_STRESS_MAX_RSS_MIB=$(AUREX_AST_STRESS_MAX_RSS_MIB) AUREX_AST_STRESS_MAX_ELAPSED_MS=$(AUREX_AST_STRESS_MAX_ELAPSED_MS) tools/ast_stress.py --skip-build
	$(PERF_THRESHOLD_ENV) AUREX_DIAGNOSTIC_STRESS_COUNTS=$(AUREX_DIAGNOSTIC_STRESS_COUNTS) AUREX_DIAGNOSTIC_STRESS_SHAPE=$(AUREX_DIAGNOSTIC_STRESS_SHAPE) AUREX_DIAGNOSTIC_STRESS_MAX_RSS_MIB=$(AUREX_DIAGNOSTIC_STRESS_MAX_RSS_MIB) AUREX_DIAGNOSTIC_STRESS_MAX_ELAPSED_MS=$(AUREX_DIAGNOSTIC_STRESS_MAX_ELAPSED_MS) tools/diagnostic_stress.py --skip-build
	AUREX_QUERY_PRUNING_GATE_FUNCTIONS=$(AUREX_QUERY_PRUNING_GATE_FUNCTIONS) tools/query_pruning_gate.py --skip-build
	AUREX_QUERY_GRAPH_FUZZ_BUILD_DIR=$(AUREX_QUERY_GRAPH_FUZZ_BUILD_DIR) tools/query_graph_fuzz.py --skip-build --rounds $(AUREX_QUERY_GRAPH_FUZZ_ROUNDS) --functions $(AUREX_QUERY_GRAPH_FUZZ_FUNCTIONS) --function-step $(AUREX_QUERY_GRAPH_FUZZ_FUNCTION_STEP)

perf-release-threshold:
	$(PERF_THRESHOLD_ENV) AUREX_STRESS_BUILD_DIR=$(AUREX_RELEASE_BUILD_DIR) AUREX_STRESS_ENABLE_LTO=ON AUREX_GENERIC_STRESS_COUNTS=$(AUREX_RELEASE_GENERIC_STRESS_COUNTS) AUREX_GENERIC_STRESS_SHAPE=$(AUREX_RELEASE_GENERIC_STRESS_SHAPE) AUREX_GENERIC_STRESS_MAX_RSS_MIB=$(AUREX_RELEASE_GENERIC_STRESS_MAX_RSS_MIB) AUREX_GENERIC_STRESS_MAX_ELAPSED_MS=$(AUREX_RELEASE_GENERIC_STRESS_MAX_ELAPSED_MS) tools/generic_stress.py
	$(PERF_THRESHOLD_ENV) AUREX_STRESS_BUILD_DIR=$(AUREX_RELEASE_BUILD_DIR) AUREX_STRESS_ENABLE_LTO=ON AUREX_AST_STRESS_COUNTS=$(AUREX_RELEASE_AST_STRESS_COUNTS) AUREX_AST_STRESS_SHAPE=$(AUREX_RELEASE_AST_STRESS_SHAPE) AUREX_AST_STRESS_MAX_RSS_MIB=$(AUREX_RELEASE_AST_STRESS_MAX_RSS_MIB) AUREX_AST_STRESS_MAX_ELAPSED_MS=$(AUREX_RELEASE_AST_STRESS_MAX_ELAPSED_MS) tools/ast_stress.py --skip-build
	$(PERF_THRESHOLD_ENV) AUREX_STRESS_BUILD_DIR=$(AUREX_RELEASE_BUILD_DIR) AUREX_STRESS_ENABLE_LTO=ON AUREX_DIAGNOSTIC_STRESS_COUNTS=$(AUREX_RELEASE_DIAGNOSTIC_STRESS_COUNTS) AUREX_DIAGNOSTIC_STRESS_SHAPE=$(AUREX_RELEASE_DIAGNOSTIC_STRESS_SHAPE) AUREX_DIAGNOSTIC_STRESS_MAX_RSS_MIB=$(AUREX_RELEASE_DIAGNOSTIC_STRESS_MAX_RSS_MIB) AUREX_DIAGNOSTIC_STRESS_MAX_ELAPSED_MS=$(AUREX_RELEASE_DIAGNOSTIC_STRESS_MAX_ELAPSED_MS) tools/diagnostic_stress.py --skip-build
	AUREX_QUERY_GRAPH_FUZZ_BUILD_DIR=$(AUREX_RELEASE_BUILD_DIR) tools/query_graph_fuzz.py --skip-build --rounds $(AUREX_QUERY_GRAPH_FUZZ_ROUNDS) --functions $(AUREX_QUERY_GRAPH_FUZZ_FUNCTIONS) --function-step $(AUREX_QUERY_GRAPH_FUZZ_FUNCTION_STEP)

perf-release-lto-threshold: perf-release-threshold

perf-release-all-threshold: perf-release-threshold

perf-ast-stress:
	tools/ast_stress.py

perf-compare:
	tools/frontend_compare.py

query-sanitizer:
	$(CMAKE) -S . -B $(AUREX_SANITIZER_BUILD_DIR) -DCMAKE_BUILD_TYPE=Debug -DAUREX_ENABLE_SANITIZERS=ON -DAUREX_ENABLE_LTO=OFF
	$(CMAKE) --build $(AUREX_SANITIZER_BUILD_DIR) --target aurexc aurex_query_tests -j
	ctest --test-dir $(AUREX_SANITIZER_BUILD_DIR) -R ^aurex_tests_query_unit$$ --output-on-failure
	AUREX_QUERY_GRAPH_FUZZ_BUILD_DIR=$(AUREX_SANITIZER_BUILD_DIR) tools/query_graph_fuzz.py --skip-build --rounds 2 --functions 8 --function-step 8

clean:
	$(CMAKE) --build $(BUILD_DIR) --target clean || true

.PHONY: all configure build test format-check bench perf perf-stress perf-stress-threshold perf-release-threshold perf-release-lto-threshold perf-release-all-threshold perf-ast-stress perf-compare query-sanitizer clean
