#include <gtest/frontend/macro/early_item_expansion/early_item_expansion_noop_fixture_support.hpp>

#include <gtest/gtest.h>

namespace aurex::test {

using namespace early_item_expansion_support;

TEST(CoreUnit, EarlyItemExpansionNoopSummaryTextCoversAllFacts)
{
    const NoopAttributeExpansionFixture fixture = make_noop_attribute_expansion_fixture();
    const frontend::macro::EarlyItemExpansionResult& result = fixture.result;

    const std::string summary = frontend::macro::summarize_early_item_expansion(result);
    expect_contains(summary,
        "early_item_expansion name=M26c Builtin Derive Cursor Rollback AST Mutation Verifier Closure");
    expect_contains(summary, "attributes=2");
    expect_contains(summary, "blocked_attributes=1");
    expect_contains(summary, "generated_part_stubs=1");
    expect_contains(summary, "parse_blocked=1");
    expect_contains(summary, "merge_blocked=1");
    expect_contains(summary, "sema_visible_generated_parts=0");
    expect_contains(summary, "hygiene_stubs=2");
    expect_contains(summary, "unresolved_hygiene_stubs=2");
    expect_contains(summary, "declared_name_stubs=2");
    expect_contains(summary, "trace_stubs=2");
    expect_contains(summary, "real_source_maps=0");
    expect_contains(summary, "debug_traces=0");
    expect_contains(summary, "cli_emit_expanded=0");
    expect_contains(summary, "generated_item_declarations=2");
    expect_contains(summary, "planned_generated_item_declarations=2");
    expect_contains(summary, "materialized_generated_items=0");
    expect_contains(summary, "declared_generated_names=2");
    expect_contains(summary, "lookup_visible_declared_names=0");
    expect_contains(summary, "export_visible_declared_names=0");
    expect_contains(summary, "token_materialization_admissions=2");
    expect_contains(summary, "compiler_owned_admissions=2");
    expect_contains(summary, "admitted_token_materializations=2");
    expect_contains(summary, "materialized_token_admissions=1");
    expect_contains(summary, "generated_token_buffers=2");
    expect_contains(summary, "empty_generated_token_buffers=1");
    expect_contains(summary, "materialized_token_buffers=1");
    expect_contains(summary, "compiler_owned_token_buffers=2");
    expect_contains(summary, "generated_token_records=7");
    expect_contains(summary, "compiler_owned_generated_token_records=7");
    expect_contains(summary, "parser_visible_generated_tokens=0");
    expect_contains(summary, "parser_admission_gates=2");
    expect_contains(summary, "compiler_owned_parser_admission_gates=2");
    expect_contains(summary, "token_record_available_gates=1");
    expect_contains(summary, "parser_blocked_token_buffers=2");
    expect_contains(summary, "parser_admitted_token_buffers=0");
    expect_contains(summary, "parser_admission_diagnostics=2");
    expect_contains(summary, "parser_admission_diagnostics_blocked=2");
    expect_contains(summary, "derive_parser_admission_diagnostics=1");
    expect_contains(summary, "empty_parser_admission_diagnostics=1");
    expect_contains(summary, "emit_expanded_projections=0");
    expect_contains(summary, "parser_admission_debug_trace_projections=0");
    expect_contains(summary, "parser_admission_source_map_projections=0");
    expect_contains(summary, "parser_admission_report_entries=2");
    expect_contains(summary, "parser_admission_reports=1");
    expect_contains(summary, "parser_admission_report_blocked_entries=2");
    expect_contains(summary, "derive_parser_admission_report_entries=1");
    expect_contains(summary, "empty_parser_admission_report_entries=1");
    expect_contains(summary, "parser_admission_report_token_record_available_entries=1");
    expect_contains(summary, "parser_admission_report_visible=1");
    expect_contains(summary, "parser_admission_report_query_reusable=1");
    expect_contains(summary, "parser_admission_report_unordered_anchors=0");
    expect_contains(summary, "parser_admission_report_parser_consumable=0");
    expect_contains(summary, "parser_readiness_preflight_entries=2");
    expect_contains(summary, "parser_readiness_preflight_blocked=2");
    expect_contains(summary, "derive_parser_readiness_preflight_entries=1");
    expect_contains(summary, "empty_parser_readiness_preflight_entries=1");
    expect_contains(summary, "parser_readiness_preflight_contiguous_indices=2");
    expect_contains(summary, "parser_readiness_preflight_delimiter_balanced=2");
    expect_contains(summary, "parser_readiness_preflight_source_anchor_covered=2");
    expect_contains(summary, "parser_readiness_preflight_parse_config_compatible=2");
    expect_contains(summary, "parser_readiness_preflight_parser_consumable=0");
    expect_contains(summary, "parser_consumption_contract_gates=1");
    expect_contains(summary, "parser_consumption_contract_blocked_gates=1");
    expect_contains(summary, "parser_consumption_contract_visible=1");
    expect_contains(summary, "parser_consumption_contract_query_reusable=1");
    expect_contains(summary, "parser_consumption_contract_parser_consumable=0");
    expect_contains(summary, "macro_boundary_closure_reports=1");
    expect_contains(summary, "macro_boundary_closure_visible=1");
    expect_contains(summary, "macro_boundary_closure_query_reusable=1");
    expect_contains(summary, "macro_boundary_closure_complete=1");
    expect_contains(summary, "macro_boundary_closure_parser_consumption_enabled=0");
    expect_contains(summary, "builtin_derive_expansion_admissions=2");
    expect_contains(summary, "builtin_derive_expansion_derive_admissions=1");
    expect_contains(summary, "builtin_derive_expansion_non_derive_blocked=1");
    expect_contains(summary, "builtin_derive_expansion_visible=2");
    expect_contains(summary, "builtin_derive_expansion_query_reusable=2");
    expect_contains(summary, "builtin_derive_expansion_capability_candidates=2");
    expect_contains(summary, "builtin_derive_semantic_plans=2");
    expect_contains(summary, "builtin_derive_semantic_plan_visible=2");
    expect_contains(summary, "builtin_derive_semantic_plan_query_reusable=2");
    expect_contains(summary, "builtin_derive_semantic_capabilities=2");
    expect_contains(summary, "builtin_derive_semantic_copy_capabilities=1");
    expect_contains(summary, "builtin_derive_semantic_eq_capabilities=1");
    expect_contains(summary, "builtin_derive_semantic_hash_capabilities=0");
    expect_contains(summary, "builtin_derive_parser_release_gates=1");
    expect_contains(summary, "builtin_derive_parser_release_visible=1");
    expect_contains(summary, "builtin_derive_parser_release_query_reusable=1");
    expect_contains(summary, "builtin_derive_parser_release_parser_consumable=0");
    expect_contains(summary, "builtin_derive_release_hardening_matrices=1");
    expect_contains(summary, "builtin_derive_release_hardening_visible=1");
    expect_contains(summary, "builtin_derive_release_hardening_query_reusable=1");
    expect_contains(summary, "builtin_derive_release_hardening_negative_matrix_complete=1");
    expect_contains(summary, "builtin_derive_release_hardening_parser_consumable=0");
    expect_contains(summary, "builtin_derive_debug_dump_contracts=1");
    expect_contains(summary, "builtin_derive_debug_dump_visible=1");
    expect_contains(summary, "builtin_derive_debug_dump_query_reusable=1");
    expect_contains(summary, "builtin_derive_debug_dump_complete=1");
    expect_contains(summary, "builtin_derive_debug_dump_parser_consumable=0");
    expect_contains(summary, "builtin_derive_rollback_diagnostic_gates=1");
    expect_contains(summary, "builtin_derive_rollback_diagnostic_visible=1");
    expect_contains(summary, "builtin_derive_rollback_diagnostic_query_reusable=1");
    expect_contains(summary, "builtin_derive_rollback_diagnostic_design_complete=1");
    expect_contains(summary, "builtin_derive_rollback_diagnostic_parser_consumable=0");
    expect_contains(summary, "builtin_derive_parser_consumption_admission_protocols=1");
    expect_contains(summary, "builtin_derive_parser_consumption_admission_visible=1");
    expect_contains(summary, "builtin_derive_parser_consumption_admission_query_reusable=1");
    expect_contains(summary, "builtin_derive_parser_consumption_admission_complete=1");
    expect_contains(summary, "builtin_derive_parser_consumption_admission_parser_consumable=0");
    expect_contains(summary, "builtin_derive_checkpoint_rollback_protocols=1");
    expect_contains(summary, "builtin_derive_checkpoint_rollback_visible=1");
    expect_contains(summary, "builtin_derive_checkpoint_rollback_query_reusable=1");
    expect_contains(summary, "builtin_derive_checkpoint_rollback_complete=1");
    expect_contains(summary, "builtin_derive_checkpoint_rollback_parser_consumable=0");
    expect_contains(summary, "builtin_derive_preconsumption_verification_closures=1");
    expect_contains(summary, "builtin_derive_preconsumption_verification_visible=1");
    expect_contains(summary, "builtin_derive_preconsumption_verification_query_reusable=1");
    expect_contains(summary, "builtin_derive_preconsumption_verification_complete=1");
    expect_contains(summary, "builtin_derive_preconsumption_verification_parser_consumable=0");
    expect_contains(summary, "builtin_derive_controlled_dry_run_adapters=1");
    expect_contains(summary, "builtin_derive_controlled_dry_run_adapter_visible=1");
    expect_contains(summary, "builtin_derive_controlled_dry_run_adapter_query_reusable=1");
    expect_contains(summary, "builtin_derive_controlled_dry_run_adapter_complete=1");
    expect_contains(summary, "builtin_derive_controlled_dry_run_adapter_executed=0");
    expect_contains(summary, "builtin_derive_dry_run_rollback_replays=1");
    expect_contains(summary, "builtin_derive_dry_run_rollback_replay_visible=1");
    expect_contains(summary, "builtin_derive_dry_run_rollback_replay_query_reusable=1");
    expect_contains(summary, "builtin_derive_dry_run_rollback_replay_complete=1");
    expect_contains(summary, "builtin_derive_dry_run_rollback_replay_executed=0");
    expect_contains(summary, "builtin_derive_dry_run_negative_matrices=1");
    expect_contains(summary, "builtin_derive_dry_run_negative_matrix_visible=1");
    expect_contains(summary, "builtin_derive_dry_run_negative_matrix_query_reusable=1");
    expect_contains(summary, "builtin_derive_dry_run_negative_matrix_complete=1");
    expect_contains(summary, "builtin_derive_dry_run_negative_matrix_parser_consumable=0");
    expect_contains(summary, "builtin_derive_parser_dry_run_sessions=1");
    expect_contains(summary, "builtin_derive_parser_dry_run_session_visible=1");
    expect_contains(summary, "builtin_derive_parser_dry_run_session_query_reusable=1");
    expect_contains(summary, "builtin_derive_parser_dry_run_session_complete=1");
    expect_contains(summary, "builtin_derive_parser_dry_run_session_executed=0");
    expect_contains(summary, "builtin_derive_parser_dry_run_session_committed=0");
    expect_contains(summary, "builtin_derive_token_cursor_snapshot_proofs=1");
    expect_contains(summary, "builtin_derive_token_cursor_snapshot_proof_visible=1");
    expect_contains(summary, "builtin_derive_token_cursor_snapshot_proof_query_reusable=1");
    expect_contains(summary, "builtin_derive_token_cursor_snapshot_proof_complete=1");
    expect_contains(summary, "builtin_derive_token_cursor_snapshot_proof_cursor_advanced=0");
    expect_contains(summary, "builtin_derive_token_cursor_snapshot_proof_committed=0");
    expect_contains(summary, "builtin_derive_diagnostic_shadow_no_ast_mutation_closures=1");
    expect_contains(summary, "builtin_derive_diagnostic_shadow_no_ast_mutation_visible=1");
    expect_contains(summary, "builtin_derive_diagnostic_shadow_no_ast_mutation_query_reusable=1");
    expect_contains(summary, "builtin_derive_diagnostic_shadow_no_ast_mutation_complete=1");
    expect_contains(summary, "builtin_derive_diagnostic_shadow_no_ast_mutation_executed=0");
    expect_contains(summary, "builtin_derive_diagnostic_shadow_no_ast_mutation_ast_mutation=0");
    expect_contains(summary, "builtin_derive_diagnostic_shadow_no_ast_mutation_parser_consumable=0");
    expect_contains(summary, "builtin_derive_parser_dry_run_admission_gates=1");
    expect_contains(summary, "builtin_derive_parser_dry_run_admission_gate_visible=1");
    expect_contains(summary, "builtin_derive_parser_dry_run_admission_gate_query_reusable=1");
    expect_contains(summary, "builtin_derive_parser_dry_run_admission_gate_complete=1");
    expect_contains(summary, "builtin_derive_parser_dry_run_admission_gate_execution_admitted=0");
    expect_contains(summary, "builtin_derive_parser_dry_run_admission_gate_executed=0");
    expect_contains(summary, "builtin_derive_parser_dry_run_admission_gate_parser_consumable=0");
    expect_contains(summary, "builtin_derive_error_recovery_shadow_diagnostic_gates=1");
    expect_contains(summary, "builtin_derive_error_recovery_shadow_diagnostic_gate_visible=1");
    expect_contains(summary, "builtin_derive_error_recovery_shadow_diagnostic_gate_query_reusable=1");
    expect_contains(summary, "builtin_derive_error_recovery_shadow_diagnostic_gate_complete=1");
    expect_contains(summary, "builtin_derive_error_recovery_shadow_diagnostic_gate_recovery_executed=0");
    expect_contains(summary, "builtin_derive_error_recovery_shadow_diagnostic_gate_diagnostic_emitted=0");
    expect_contains(summary, "builtin_derive_error_recovery_shadow_diagnostic_gate_parser_consumable=0");
    expect_contains(summary, "builtin_derive_cursor_rollback_ast_mutation_verifier_closures=1");
    expect_contains(summary, "builtin_derive_cursor_rollback_ast_mutation_verifier_visible=1");
    expect_contains(summary, "builtin_derive_cursor_rollback_ast_mutation_verifier_query_reusable=1");
    expect_contains(summary, "builtin_derive_cursor_rollback_ast_mutation_verifier_complete=1");
    expect_contains(summary, "builtin_derive_cursor_rollback_ast_mutation_verifier_rollback_executed=0");
    expect_contains(summary, "builtin_derive_cursor_rollback_ast_mutation_verifier_ast_mutation=0");
    expect_contains(summary, "builtin_derive_cursor_rollback_ast_mutation_verifier_parser_consumable=0");
    expect_contains(summary, "generated_source_text=0");
    expect_contains(summary, "parse_ready_token_buffers=0");
    expect_contains(summary, "ast_mutations=0");
    expect_contains(summary, "user_generated_code=0");
}

TEST(CoreUnit, EarlyItemExpansionNoopDumpTextCoversAllFacts)
{
    const NoopAttributeExpansionFixture fixture = make_noop_attribute_expansion_fixture();
    const frontend::macro::EarlyItemExpansionResult& result = fixture.result;

    const std::string dump = frontend::macro::dump_early_item_expansion(result);
    expect_contains(dump, "input #0");
    expect_contains(dump, "attr=builder");
    expect_contains(dump, "disposition=blocked_unimplemented_attribute");
    expect_contains(dump, "generated_part #0");
    expect_contains(dump, "source_role=generated");
    expect_contains(dump, "kind=generated");
    expect_contains(dump, "parse_merge_stub #0");
    expect_contains(dump, "lifecycle=merge_blocked");
    expect_contains(dump, "materialized_buffer=yes");
    expect_contains(dump, "sema_visible=no");
    expect_contains(dump, "parse and merge are blocked in M21e");
    expect_contains(dump, "buffer_identity=");
    expect_contains(dump, "parse_config=");
    expect_contains(dump, "merge_ordering=");
    expect_contains(dump, "source_map #1");
    expect_contains(dump, "hygiene_stub #0");
    expect_contains(dump, "policy=origin_mark_hygiene_v1");
    expect_contains(dump, "resolved=no");
    expect_contains(dump, "declared_names_visible=no");
    expect_contains(dump, "captures_call_site_locals=no");
    expect_contains(dump, "call_site_mark=");
    expect_contains(dump, "definition_site_mark=");
    expect_contains(dump, "generated_fresh_mark=");
    expect_contains(dump, "declared_name_set=");
    expect_contains(dump, "trace_stub #0");
    expect_contains(dump, "policy=expansion_source_map_debug_trace_v1");
    expect_contains(dump, "cli_emit_expanded=no");
    expect_contains(dump, "real macro source map and debug trace are blocked in M21f");
    expect_contains(dump, "trace_identity=");
    expect_contains(dump, "generated_source_map=");
    expect_contains(dump, "diagnostic_anchor=");
    expect_contains(dump, "generated_item_declaration_stub #0");
    expect_contains(dump, "role=attached_item_codegen_declared_names_v1");
    expect_contains(dump, "name=__aurex_macro_declared:0:0:0:0:builder");
    expect_contains(dump, "planned=yes");
    expect_contains(dump, "materialized_tokens=no");
    expect_contains(dump, "generated item declaration materialization is blocked in M21g");
    expect_contains(dump, "declaration_identity=");
    expect_contains(dump, "generated_item_key=");
    expect_contains(dump, "declared_generated_name_stub #0");
    expect_contains(dump, "namespace=item");
    expect_contains(dump, "lookup_visible=no");
    expect_contains(dump, "export_visible=no");
    expect_contains(dump, "declared generated name lookup is blocked in M21g");
    expect_contains(dump, "declared_name_identity=");
    expect_contains(dump, "hygiene_mark=");
    expect_contains(dump, "token_materialization_admission_stub #0");
    expect_contains(dump, "policy=compiler_owned_attached_item_token_materialization_admission_v1");
    expect_contains(dump, "token_stream=m21h-token-stream:0:0:0:0:builder");
    expect_contains(dump, "compiler_owned=yes");
    expect_contains(dump, "admitted=yes");
    expect_contains(dump, "generated_source_text=no");
    expect_contains(dump, "parse_ready=no");
    expect_contains(dump, "external_process_required=no");
    expect_contains(dump, "standard_library_required=no");
    expect_contains(dump, "runtime_required=no");
    expect_contains(dump, "non-derive item attribute token materialization remains blocked in M21i");
    expect_contains(dump, "source_map_identity=");
    expect_contains(dump, "token_plan_identity=");
    expect_contains(dump, "token_buffer_identity=");
    expect_contains(dump, "generated_token_buffer_stub #0");
    expect_contains(dump, "kind=compiler_owned_empty_token_stream");
    expect_contains(dump, "producer=compiler_owned_blocked_empty_token_producer_v1");
    expect_contains(dump, "token_count=0");
    expect_contains(dump, "empty=yes");
    expect_contains(dump, "parser_consumable=no");
    expect_contains(dump, "materialization_identity=");
    expect_contains(dump, "generated token buffer remains empty and parser-blocked in M21i");
    expect_contains(dump, "kind=compiler_owned_builtin_derive_token_stream_prototype");
    expect_contains(dump, "producer=compiler_owned_builtin_derive_token_producer_prototype_v1");
    expect_contains(dump, "generated_token_record #0");
    expect_contains(dump, "text=__aurex_builtin_derive_begin");
    expect_contains(dump, "role=derive_codegen_begin");
    expect_contains(dump, "role=derive_source_token_placeholder");
    expect_contains(dump, "text=__aurex_builtin_derive_end");
    expect_contains(dump, "parser_visible=no");
    expect_contains(dump, "token_identity=");
    expect_contains(dump, "generated_token_parser_admission_gate_stub #0");
    expect_contains(dump, "policy=compiler_owned_generated_token_parser_admission_gate_v1");
    expect_contains(dump, "token_buffer_materialized=no");
    expect_contains(dump, "token_records_available=no");
    expect_contains(dump, "parser_admitted=no");
    expect_contains(dump, "generated_part_parsed=no");
    expect_contains(dump, "generated_part_merged=no");
    expect_contains(dump, "empty or non-derive generated token buffer parser admission remains blocked in M21j");
    expect_contains(dump, "compiler-owned derive generated token buffer parser admission remains blocked in M21j");
    expect_contains(dump, "generated_buffer_identity=");
    expect_contains(dump, "parse_gate_identity=");
    expect_contains(dump, "parser_admission_diagnostic_projection_stub #0");
    expect_contains(dump, "policy=parser_admission_blocked_diagnostic_projection_v1");
    expect_contains(dump, "category=empty_token_buffer_parser_admission_blocked");
    expect_contains(dump, "category=derive_token_buffer_parser_admission_blocked");
    expect_contains(dump, "debug_projection=m21k-parser-admission:0:0:0:0:builder");
    expect_contains(dump, "debug_projection=m21k-parser-admission:0:0:0:1:derive");
    expect_contains(dump, "primary_anchor=");
    expect_contains(dump, "token_tree_anchor=");
    expect_contains(dump, "emit_expanded_available=no");
    expect_contains(dump, "debug_trace_available=no");
    expect_contains(dump, "source_map_available=no");
    expect_contains(dump, "token_buffer_blocker=empty or non-derive generated token buffer parser admission remains blocked in M21j");
    expect_contains(dump, "generated_part_parse_blocker=generated module part parse remains blocked before parser admission diagnostics in M21k");
    expect_contains(dump, "message=generated token buffer is empty and parser admission remains blocked in M21k");
    expect_contains(dump, "message=generated derive token buffer is compiler-owned but parser admission remains blocked in M21k");
    expect_contains(dump, "diagnostic_identity=");
    expect_contains(dump, "diagnostic_anchor=");
    expect_contains(dump, "trace_identity=");
    expect_contains(dump, "parser_admission_report_entry #0");
    expect_contains(dump, "report_index=0");
    expect_contains(dump, "report_index=1");
    expect_contains(dump, "query_projection=m21l-parser-admission-report:0:0");
    expect_contains(dump, "report_visible=yes");
    expect_contains(dump, "query_reusable=yes");
    expect_contains(dump, "report_entry_identity=");
    expect_contains(dump, "parser_admission_diagnostic_report #0");
    expect_contains(dump, "policy=parser_admission_blocked_report_query_projection_v1");
    expect_contains(dump, "query=m21l-parser-admission-report:0:0");
    expect_contains(dump, "entries=2");
    expect_contains(dump, "blocked_entries=2");
    expect_contains(dump, "derive_entries=1");
    expect_contains(dump, "empty_entries=1");
    expect_contains(dump, "token_record_available_entries=1");
    expect_contains(dump, "source_anchor_ordered=yes");
    expect_contains(dump, "parser admission diagnostic report remains parser-blocked in M21l");
    expect_contains(dump, "report_identity=");
    expect_contains(dump, "report_anchor_identity=");
    expect_contains(dump, "report_grouping_identity=");
    expect_contains(dump, "parser_readiness_preflight_entry #0");
    expect_contains(dump, "shape=empty_token_stream_parser_input_blocked");
    expect_contains(dump, "shape=derive_token_buffer_parser_input_candidate");
    expect_contains(dump, "token_indices_contiguous=yes");
    expect_contains(dump, "delimiter_balance=balanced");
    expect_contains(dump, "source_anchor_coverage=covered");
    expect_contains(dump, "parse_config_compatible=yes");
    expect_contains(dump, "hygiene_prerequisite_available=yes");
    expect_contains(dump, "source_map_prerequisite_available=yes");
    expect_contains(dump, "diagnostic_projection_available=yes");
    expect_contains(dump, "policy=generated_token_parser_consumption_readiness_preflight_v1");
    expect_contains(dump, "parser consumption readiness preflight remains parser-blocked in M21m");
    expect_contains(dump, "preflight_identity=");
    expect_contains(dump, "parser_consumption_contract_gate #0");
    expect_contains(dump, "policy=generated_token_parser_consumption_contract_gate_v1");
    expect_contains(dump, "query=m21n-parser-consumption-contract:0:0");
    expect_contains(dump, "preflight_entries=2");
    expect_contains(dump, "all_entries_structurally_checked=yes");
    expect_contains(dump, "parser consumption contract remains parser-blocked in M21n");
    expect_contains(dump, "contract_identity=");
    expect_contains(dump, "contract_grouping_identity=");
    expect_contains(dump, "contract_anchor_identity=");
    expect_contains(dump, "macro_boundary_closure_report #0");
    expect_contains(dump, "policy=m21_macro_expansion_boundary_release_closure_v1");
    expect_contains(dump, "query=m21o-macro-boundary-closure");
    expect_contains(dump, "release_closure_complete=yes");
    expect_contains(dump, "parser_consumption_enabled=no");
    expect_contains(dump, "M21 macro expansion boundary remains parser-blocked after M21o closure");
    expect_contains(dump, "closure_identity=");
    expect_contains(dump, "closure_grouping_identity=");
    expect_contains(dump, "builtin_derive_expansion_admission_gate #0");
    expect_contains(dump, "policy=builtin_derive_expansion_admission_gate_v1");
    expect_contains(dump, "kind=non_derive_attribute_expansion_blocked");
    expect_contains(dump, "kind=builtin_derive_expansion_candidate");
    expect_contains(dump, "query=m22a-builtin-derive-admission:0:0:0:1:derive");
    expect_contains(dump, "capability_candidates=2");
    expect_contains(dump, "builtin derive expansion admission remains parser-blocked in M22a");
    expect_contains(dump, "admission_identity=");
    expect_contains(dump, "builtin_derive_semantic_expansion_plan #0");
    expect_contains(dump, "policy=builtin_derive_semantic_expansion_plan_v1");
    expect_contains(dump, "target_kind=struct");
    expect_contains(dump, "semantic_model=capability_fact_lowering_plan");
    expect_contains(dump, "copy=1");
    expect_contains(dump, "eq=1");
    expect_contains(dump, "hash=0");
    expect_contains(dump, "requires_generated_items=no");
    expect_contains(dump, "requires_standard_library=no");
    expect_contains(dump, "requires_runtime=no");
    expect_contains(dump, "builtin derive semantic expansion remains capability-only and parser-blocked in M22b");
    expect_contains(dump, "capability_set_identity=");
    expect_contains(dump, "semantic_plan_identity=");
    expect_contains(dump, "builtin_derive_parser_consumption_release_gate #0");
    expect_contains(dump, "policy=builtin_derive_parser_consumption_release_gate_v1");
    expect_contains(dump, "query=m22c-builtin-derive-parser-release:0:0");
    expect_contains(dump, "admissions=2");
    expect_contains(dump, "derive_admissions=1");
    expect_contains(dump, "semantic_plans=2");
    expect_contains(dump, "capabilities=2");
    expect_contains(dump, "parser_consumable_contracts=0");
    expect_contains(dump, "rollback_diagnostics_available=yes");
    expect_contains(dump, "builtin derive parser consumption release remains blocked in M22c");
    expect_contains(dump, "release_gate_identity=");
    expect_contains(dump, "builtin_derive_release_hardening_matrix #0");
    expect_contains(dump, "policy=builtin_derive_release_hardening_matrix_v1");
    expect_contains(dump, "query=m22d-builtin-derive-release-hardening:0:0");
    expect_contains(dump, "part_local_admissions=2");
    expect_contains(dump, "global_admissions=2");
    expect_contains(dump, "cross_part_admissions=0");
    expect_contains(dump, "negative_matrix_complete=yes");
    expect_contains(dump, "release_remains_blocked=yes");
    expect_contains(dump, "builtin derive release hardening matrix keeps parser consumption blocked in M22d");
    expect_contains(dump, "hardening_matrix_identity=");
    expect_contains(dump, "builtin_derive_debug_dump_stability_contract #0");
    expect_contains(dump, "policy=builtin_derive_debug_dump_stability_contract_v1");
    expect_contains(dump, "query=m22e-builtin-derive-debug-dump:0:0");
    expect_contains(dump, "dump_sections=4");
    expect_contains(dump, "stable_ordering_available=yes");
    expect_contains(dump, "identity_projection_available=yes");
    expect_contains(dump, "debug_dump_contract_complete=yes");
    expect_contains(dump, "builtin derive debug dump stability remains facts-only and parser-blocked in M22e");
    expect_contains(dump, "debug_dump_contract_identity=");
    expect_contains(dump, "builtin_derive_rollback_diagnostic_design_gate #0");
    expect_contains(dump, "policy=builtin_derive_rollback_diagnostic_design_gate_v1");
    expect_contains(dump, "query=m22f-builtin-derive-rollback-diagnostic:0:0");
    expect_contains(dump, "diagnostic_projections=2");
    expect_contains(dump, "blocked_diagnostics=2");
    expect_contains(dump, "derive_diagnostics=1");
    expect_contains(dump, "empty_diagnostics=1");
    expect_contains(dump, "rollback_execution_enabled=no");
    expect_contains(dump, "builtin derive rollback diagnostics remain design-only and parser-blocked in M22f");
    expect_contains(dump, "rollback_gate_identity=");
    expect_contains(dump, "builtin_derive_parser_consumption_admission_protocol #0");
    expect_contains(dump, "policy=builtin_derive_parser_consumption_admission_protocol_v1");
    expect_contains(dump, "query=m23a-builtin-derive-parser-consumption-admission:0:0");
    expect_contains(dump, "token_buffers=2");
    expect_contains(dump, "derive_candidates=1");
    expect_contains(dump, "empty_candidates=1");
    expect_contains(dump, "parser_admitted=no");
    expect_contains(dump,
        "builtin derive parser consumption admission protocol remains no-parser-consumption in M23a");
    expect_contains(dump, "admission_protocol_identity=");
    expect_contains(dump, "builtin_derive_checkpoint_rollback_protocol #0");
    expect_contains(dump, "policy=builtin_derive_parser_checkpoint_rollback_protocol_v1");
    expect_contains(dump, "query=m23b-builtin-derive-checkpoint-rollback:0:0");
    expect_contains(dump, "checkpoints=3");
    expect_contains(dump, "rollback_plans=3");
    expect_contains(dump, "diagnostic_replay_available=yes");
    expect_contains(dump,
        "builtin derive checkpoint rollback protocol remains design-only and parser-blocked in M23b");
    expect_contains(dump, "checkpoint_protocol_identity=");
    expect_contains(dump, "builtin_derive_preconsumption_verification_closure #0");
    expect_contains(dump, "policy=builtin_derive_parser_preconsumption_verification_closure_v1");
    expect_contains(dump, "query=m23c-builtin-derive-preconsumption-verification:0:0");
    expect_contains(dump, "verification_closure_complete=yes");
    expect_contains(dump, "sema_visible=no");
    expect_contains(dump,
        "builtin derive pre-consumption verification closure keeps parser consumption blocked in M23c");
    expect_contains(dump, "verification_closure_identity=");
    expect_contains(dump, "builtin_derive_controlled_dry_run_adapter #0");
    expect_contains(dump, "policy=builtin_derive_controlled_parser_dry_run_adapter_v1");
    expect_contains(dump, "query=m24a-builtin-derive-controlled-parser-dry-run:0:0");
    expect_contains(dump, "prerequisites=5");
    expect_contains(dump, "dry_run_adapter_complete=yes");
    expect_contains(dump, "dry_run_executed=no");
    expect_contains(dump,
        "builtin derive controlled parser dry-run adapter remains execution-blocked in M24a");
    expect_contains(dump, "dry_run_adapter_identity=");
    expect_contains(dump, "builtin_derive_dry_run_rollback_replay #0");
    expect_contains(dump, "policy=builtin_derive_dry_run_rollback_diagnostic_replay_v1");
    expect_contains(dump, "query=m24b-builtin-derive-dry-run-rollback-replay:0:0");
    expect_contains(dump, "planned_replays=2");
    expect_contains(dump, "executed_replays=0");
    expect_contains(dump, "replay_execution_enabled=no");
    expect_contains(dump,
        "builtin derive dry-run rollback diagnostic replay remains execution-blocked in M24b");
    expect_contains(dump, "replay_protocol_identity=");
    expect_contains(dump, "builtin_derive_dry_run_negative_matrix #0");
    expect_contains(dump, "policy=builtin_derive_dry_run_negative_matrix_closure_v1");
    expect_contains(dump, "query=m24c-builtin-derive-dry-run-negative-matrix:0:0");
    expect_contains(dump, "negative_cases=8");
    expect_contains(dump, "parser_consumable_cases=0");
    expect_contains(dump, "negative_matrix_complete=yes");
    expect_contains(dump,
        "builtin derive dry-run negative matrix keeps parser consumption blocked in M24c");
    expect_contains(dump, "negative_matrix_identity=");
    expect_contains(dump, "builtin_derive_parser_dry_run_session #0");
    expect_contains(dump, "policy=builtin_derive_parser_dry_run_session_boundary_v1");
    expect_contains(dump, "query=m25a-builtin-derive-dry-run-session:0:0");
    expect_contains(dump, "token_buffer_candidates=1");
    expect_contains(dump, "parser_state_snapshots=1");
    expect_contains(dump, "committed_parses=0");
    expect_contains(dump, "sandbox_available=yes");
    expect_contains(dump, "check_only=yes");
    expect_contains(dump, "session_committed=no");
    expect_contains(dump,
        "builtin derive parser dry-run session remains check-only and uncommitted in M25a");
    expect_contains(dump, "dry_run_session_identity=");
    expect_contains(dump, "builtin_derive_token_cursor_snapshot_proof #0");
    expect_contains(dump, "policy=builtin_derive_token_cursor_snapshot_rollback_proof_v1");
    expect_contains(dump, "query=m25b-builtin-derive-token-cursor-rollback-proof:0:0");
    expect_contains(dump, "cursor_snapshots=3");
    expect_contains(dump, "parser_state_snapshots=3");
    expect_contains(dump, "rollback_proofs=3");
    expect_contains(dump, "cursor_commits=0");
    expect_contains(dump, "parser_cursor_advanced=no");
    expect_contains(dump,
        "builtin derive token cursor snapshot rollback proof keeps parser cursor unadvanced in M25b");
    expect_contains(dump, "cursor_snapshot_identity=");
    expect_contains(dump, "builtin_derive_diagnostic_shadow_no_ast_mutation_closure #0");
    expect_contains(dump, "policy=builtin_derive_diagnostic_shadow_no_ast_mutation_closure_v1");
    expect_contains(dump, "query=m25c-builtin-derive-diagnostic-shadow-no-ast-mutation:0:0");
    expect_contains(dump, "diagnostic_shadows=2");
    expect_contains(dump, "executed_shadows=0");
    expect_contains(dump, "ast_mutations=0");
    expect_contains(dump, "no_ast_mutation_verified=yes");
    expect_contains(dump,
        "builtin derive diagnostic shadow replay remains non-executing and no-AST-mutation in M25c");
    expect_contains(dump, "closure_identity=");
}
} // namespace aurex::test
