#include "aurex/codegen_c/c_emitter.hpp"

#include <unordered_set>
#include <utility>

namespace aurex::codegen_c {

namespace {

[[nodiscard]] std::string binary_op_text(const syntax::BinaryOp op) {
    switch (op) {
    case syntax::BinaryOp::add: return "+";
    case syntax::BinaryOp::sub: return "-";
    case syntax::BinaryOp::mul: return "*";
    case syntax::BinaryOp::div: return "/";
    case syntax::BinaryOp::mod: return "%";
    case syntax::BinaryOp::shl: return "<<";
    case syntax::BinaryOp::shr: return ">>";
    case syntax::BinaryOp::less: return "<";
    case syntax::BinaryOp::less_equal: return "<=";
    case syntax::BinaryOp::greater: return ">";
    case syntax::BinaryOp::greater_equal: return ">=";
    case syntax::BinaryOp::equal: return "==";
    case syntax::BinaryOp::not_equal: return "!=";
    case syntax::BinaryOp::bit_and: return "&";
    case syntax::BinaryOp::bit_xor: return "^";
    case syntax::BinaryOp::bit_or: return "|";
    case syntax::BinaryOp::logical_and: return "&&";
    case syntax::BinaryOp::logical_or: return "||";
    }
    return "?";
}

[[nodiscard]] std::string unary_op_text(const syntax::UnaryOp op) {
    switch (op) {
    case syntax::UnaryOp::logical_not: return "!";
    case syntax::UnaryOp::numeric_negate: return "-";
    case syntax::UnaryOp::bitwise_not: return "~";
    case syntax::UnaryOp::address_of: return "&";
    case syntax::UnaryOp::dereference: return "*";
    }
    return "?";
}

[[nodiscard]] std::unordered_set<base::u32> collect_nested_extern_items(const syntax::AstModule& module) {
    std::unordered_set<base::u32> nested;
    for (const syntax::ItemNode& item : module.items) {
        if (item.kind != syntax::ItemKind::extern_block) {
            continue;
        }
        for (syntax::ItemId id : item.extern_items) {
            if (syntax::is_valid(id)) {
                nested.insert(id.value);
            }
        }
    }
    return nested;
}

} // namespace

CEmitter::CEmitter(const syntax::AstModule& module, const sema::CheckedModule& checked) noexcept
    : module_(module), checked_(checked) {}

base::Result<COutput> CEmitter::emit() {
    static_cast<void>(checked_);
    emit_prelude();
    emit_forward_decls();
    const std::unordered_set<base::u32> nested = collect_nested_extern_items(module_);
    for (base::u32 i = 0; i < module_.items.size(); ++i) {
        if (nested.contains(i)) {
            continue;
        }
        emit_item(module_.items[i]);
    }
    return base::Result<COutput>::ok(COutput {out_.str()});
}

void CEmitter::emit_prelude() {
    out_ << "#include <stdint.h>\n";
    out_ << "#include <stddef.h>\n";
    out_ << "#include <stdbool.h>\n\n";
    out_ << "/* Generated by Aurex M0V0.1.8. */\n\n";
}

void CEmitter::emit_forward_decls() {
    const std::unordered_set<base::u32> nested = collect_nested_extern_items(module_);
    for (base::u32 i = 0; i < module_.items.size(); ++i) {
        if (nested.contains(i)) {
            continue;
        }
        const syntax::ItemNode& item = module_.items[i];
        if (item.kind == syntax::ItemKind::struct_decl) {
            out_ << "typedef struct " << item.name << " " << item.name << ";\n";
        } else if (item.kind == syntax::ItemKind::opaque_struct_decl) {
            out_ << "typedef struct " << item.name << " " << item.name << ";\n";
        } else if (item.kind == syntax::ItemKind::extern_block) {
            for (syntax::ItemId id : item.extern_items) {
                const syntax::ItemNode& child = module_.items[id.value];
                if (child.kind == syntax::ItemKind::opaque_struct_decl) {
                    out_ << "typedef struct " << child.name << " " << child.name << ";\n";
                }
            }
        }
    }
    out_ << "\n";
}

void CEmitter::emit_item(const syntax::ItemNode& item) {
    switch (item.kind) {
    case syntax::ItemKind::const_decl:
        emit_const(item);
        break;
    case syntax::ItemKind::struct_decl:
        emit_struct(item);
        break;
    case syntax::ItemKind::enum_decl:
        emit_enum(item);
        break;
    case syntax::ItemKind::opaque_struct_decl:
        break;
    case syntax::ItemKind::fn_decl:
        if (item.is_extern_c) {
            emit_function_decl(item, true);
        } else if (is_exported_main(item)) {
            emit_main_wrapper(item);
        } else {
            emit_function_decl(item, false);
            out_ << " ";
            emit_block(item.body);
            out_ << "\n";
        }
        break;
    case syntax::ItemKind::extern_block:
        for (syntax::ItemId id : item.extern_items) {
            emit_item(module_.items[id.value]);
        }
        out_ << "\n";
        break;
    }
}

void CEmitter::emit_const(const syntax::ItemNode& item) {
    out_ << "static const " << emit_type(item.const_type, std::string(item.name))
         << " = " << emit_expr(item.const_value) << ";\n\n";
}

void CEmitter::emit_struct(const syntax::ItemNode& item) {
    out_ << "typedef struct " << item.name << " {\n";
    ++indent_;
    for (const syntax::FieldDecl& field : item.fields) {
        write_indent();
        out_ << emit_type(field.type, std::string(field.name)) << ";\n";
    }
    --indent_;
    out_ << "} " << item.name << ";\n\n";
}

void CEmitter::emit_enum(const syntax::ItemNode& item) {
    out_ << "typedef " << emit_type(item.enum_base_type) << " " << item.name << ";\n";
    out_ << "enum {\n";
    ++indent_;
    for (const syntax::EnumCaseDecl& enum_case : item.enum_cases) {
        write_indent();
        out_ << item.name << "_" << enum_case.name << " = " << enum_case.value_text << ",\n";
    }
    --indent_;
    out_ << "};\n\n";
}

void CEmitter::emit_function_decl(const syntax::ItemNode& item, const bool with_semicolon) {
    emit_function_decl_named(item, c_name(item), with_semicolon);
}

void CEmitter::emit_function_decl_named(const syntax::ItemNode& item, const std::string_view name, const bool with_semicolon) {
    out_ << emit_type(item.return_type) << " " << name << "(";
    for (base::usize i = 0; i < item.params.size(); ++i) {
        if (i != 0) {
            out_ << ", ";
        }
        const syntax::ParamDecl& param = item.params[i];
        out_ << emit_type(param.type, std::string(param.name));
    }
    out_ << ")";
    if (with_semicolon) {
        out_ << ";\n";
    }
}

void CEmitter::emit_main_wrapper(const syntax::ItemNode& item) {
    out_ << "static ";
    emit_function_decl_named(item, "aurex_m0_main", false);
    out_ << " ";
    emit_block(item.body);
    out_ << "\n";
    out_ << "int main(int argc, char **argv) {\n";
    out_ << "    return (int)aurex_m0_main((int32_t)argc, (uint8_t **)argv);\n";
    out_ << "}\n";
}

void CEmitter::emit_block(const syntax::StmtId block_id) {
    out_ << "{\n";
    ++indent_;
    if (syntax::is_valid(block_id) && block_id.value < module_.stmts.size()) {
        const syntax::StmtNode& block = module_.stmts[block_id.value];
        for (syntax::StmtId stmt : block.statements) {
            emit_stmt(stmt);
        }
    }
    --indent_;
    write_indent();
    out_ << "}\n";
}

void CEmitter::emit_stmt(const syntax::StmtId stmt_id) {
    if (!syntax::is_valid(stmt_id) || stmt_id.value >= module_.stmts.size()) {
        return;
    }
    const syntax::StmtNode& stmt = module_.stmts[stmt_id.value];
    write_indent();
    switch (stmt.kind) {
    case syntax::StmtKind::let:
    case syntax::StmtKind::var:
        out_ << emit_type(stmt.declared_type, std::string(stmt.name)) << " = " << emit_expr(stmt.init) << ";\n";
        break;
    case syntax::StmtKind::assign:
        out_ << emit_expr(stmt.lhs) << " = " << emit_expr(stmt.rhs) << ";\n";
        break;
    case syntax::StmtKind::if_:
        out_ << "if " << emit_condition(stmt.condition) << " ";
        emit_block(stmt.then_block);
        if (syntax::is_valid(stmt.else_block)) {
            write_indent();
            out_ << "else ";
            emit_block(stmt.else_block);
        }
        break;
    case syntax::StmtKind::while_:
        out_ << "while " << emit_condition(stmt.condition) << " ";
        emit_block(stmt.body);
        break;
    case syntax::StmtKind::break_:
        out_ << "break;\n";
        break;
    case syntax::StmtKind::continue_:
        out_ << "continue;\n";
        break;
    case syntax::StmtKind::return_:
        if (syntax::is_valid(stmt.return_value)) {
            out_ << "return " << emit_expr(stmt.return_value) << ";\n";
        } else {
            out_ << "return;\n";
        }
        break;
    case syntax::StmtKind::expr:
        out_ << emit_expr(stmt.init) << ";\n";
        break;
    case syntax::StmtKind::block:
        emit_block(stmt_id);
        break;
    }
}

std::string CEmitter::emit_expr(syntax::ExprId expr_id) {
    if (!syntax::is_valid(expr_id) || expr_id.value >= module_.exprs.size()) {
        return "/*invalid*/0";
    }
    const syntax::ExprNode& expr = module_.exprs[expr_id.value];
    switch (expr.kind) {
    case syntax::ExprKind::integer_literal:
    case syntax::ExprKind::bool_literal:
        return std::string(expr.text);
    case syntax::ExprKind::null_literal:
        return "NULL";
    case syntax::ExprKind::string_literal:
        return std::string(expr.text);
    case syntax::ExprKind::c_string_literal:
        return "(const uint8_t *)" + escape_c_string(expr.text.substr(1));
    case syntax::ExprKind::byte_literal:
        return std::string(expr.text.substr(1));
    case syntax::ExprKind::name:
        return std::string(expr.text);
    case syntax::ExprKind::unary:
        return "(" + unary_op_text(expr.unary_op) + emit_expr(expr.unary_operand) + ")";
    case syntax::ExprKind::binary:
        return "(" + emit_expr(expr.binary_lhs) + " " + binary_op_text(expr.binary_op) + " " + emit_expr(expr.binary_rhs) + ")";
    case syntax::ExprKind::call: {
        std::string result = emit_callee(expr.callee);
        result += "(";
        for (base::usize i = 0; i < expr.args.size(); ++i) {
            if (i != 0) {
                result += ", ";
            }
            result += emit_expr(expr.args[i]);
        }
        result += ")";
        return result;
    }
    case syntax::ExprKind::field:
        return emit_expr(expr.object) + (expr_has_pointer_type(expr.object) ? "->" : ".") + std::string(expr.field_name);
    case syntax::ExprKind::index:
        return emit_expr(expr.object) + "[" + emit_expr(expr.index) + "]";
    case syntax::ExprKind::struct_literal: {
        std::string result = "(" + std::string(expr.struct_name) + "){";
        for (base::usize i = 0; i < expr.field_inits.size(); ++i) {
            if (i != 0) {
                result += ", ";
            }
            result += "." + std::string(expr.field_inits[i].name) + " = " + emit_expr(expr.field_inits[i].value);
        }
        result += "}";
        return result;
    }
    case syntax::ExprKind::cast:
    case syntax::ExprKind::ptr_cast:
    case syntax::ExprKind::bit_cast:
        return "((" + emit_type(expr.cast_type) + ")(" + emit_expr(expr.cast_expr) + "))";
    case syntax::ExprKind::invalid:
        return "/*invalid*/0";
    }
    return "/*unknown*/0";
}

std::string CEmitter::emit_condition(const syntax::ExprId expr_id) {
    const std::string value = emit_expr(expr_id);
    if (!value.empty() && value.front() == '(' && value.back() == ')') {
        return value;
    }
    return "(" + value + ")";
}

std::string CEmitter::emit_type(syntax::TypeId type_id, std::string declarator) {
    if (!syntax::is_valid(type_id) || type_id.value >= module_.types.size()) {
        return "void" + (declarator.empty() ? "" : " " + declarator);
    }
    const syntax::TypeNode& type = module_.types[type_id.value];
    switch (type.kind) {
    case syntax::TypeKind::primitive: {
        const std::string primitive = emit_primitive(type.primitive);
        return declarator.empty() ? primitive : primitive + " " + declarator;
    }
    case syntax::TypeKind::named:
        return declarator.empty() ? std::string(type.name) : std::string(type.name) + " " + declarator;
    case syntax::TypeKind::pointer: {
        const syntax::TypeNode& pointee = module_.types[type.pointee.value];
        if (pointee.kind == syntax::TypeKind::array) {
            std::string inner = "(*" + declarator + ")";
            if (type.pointer_mutability == syntax::PointerMutability::const_) {
                inner = "const " + inner;
            }
            return emit_type(type.pointee, inner);
        }
        const std::string pointer_decl = "*" + declarator;
        const std::string emitted = emit_type(type.pointee, pointer_decl);
        if (type.pointer_mutability == syntax::PointerMutability::const_) {
            if (pointee.kind == syntax::TypeKind::primitive && pointee.primitive == syntax::PrimitiveTypeKind::void_) {
                return declarator.empty() ? "const void *" : "const void *" + declarator;
            }
            return "const " + emitted;
        }
        return emitted;
    }
    case syntax::TypeKind::array: {
        std::string array_decl = declarator + "[" + std::to_string(type.array_count) + "]";
        return emit_type(type.array_element, array_decl);
    }
    }
    return "void";
}

std::string CEmitter::emit_primitive(const syntax::PrimitiveTypeKind primitive) const {
    switch (primitive) {
    case syntax::PrimitiveTypeKind::void_: return "void";
    case syntax::PrimitiveTypeKind::bool_: return "bool";
    case syntax::PrimitiveTypeKind::i8: return "int8_t";
    case syntax::PrimitiveTypeKind::u8: return "uint8_t";
    case syntax::PrimitiveTypeKind::i16: return "int16_t";
    case syntax::PrimitiveTypeKind::u16: return "uint16_t";
    case syntax::PrimitiveTypeKind::i32: return "int32_t";
    case syntax::PrimitiveTypeKind::u32: return "uint32_t";
    case syntax::PrimitiveTypeKind::i64: return "int64_t";
    case syntax::PrimitiveTypeKind::u64: return "uint64_t";
    case syntax::PrimitiveTypeKind::isize: return "ptrdiff_t";
    case syntax::PrimitiveTypeKind::usize: return "size_t";
    case syntax::PrimitiveTypeKind::f32: return "float";
    case syntax::PrimitiveTypeKind::f64: return "double";
    case syntax::PrimitiveTypeKind::str: return "const char*";
    }
    return "void";
}

std::string CEmitter::emit_callee(const syntax::ExprId callee) const {
    if (!syntax::is_valid(callee) || callee.value >= module_.exprs.size()) {
        return "/*invalid_callee*/";
    }
    const syntax::ExprNode& expr = module_.exprs[callee.value];
    if (expr.kind != syntax::ExprKind::name) {
        return std::string(expr.text);
    }
    const auto found = checked_.functions.find(std::string(expr.text));
    if (found == checked_.functions.end()) {
        return std::string(expr.text);
    }
    return found->second.c_name;
}

std::string CEmitter::c_name(const syntax::ItemNode& item) const {
    if (!item.abi_name.empty()) {
        return std::string(item.abi_name);
    }
    return std::string(item.name);
}

std::string CEmitter::escape_c_string(const std::string_view literal) const {
    return std::string(literal);
}

bool CEmitter::is_exported_main(const syntax::ItemNode& item) const noexcept {
    return item.kind == syntax::ItemKind::fn_decl && item.is_export_c && item.name == "main";
}

bool CEmitter::expr_has_pointer_type(const syntax::ExprId expr) const noexcept {
    if (!syntax::is_valid(expr) || expr.value >= checked_.expr_types.size()) {
        return false;
    }
    const sema::TypeHandle type = checked_.expr_types[expr.value];
    return sema::is_valid(type) && checked_.types.is_pointer(type);
}

void CEmitter::write_indent() {
    for (int i = 0; i < indent_; ++i) {
        out_ << "    ";
    }
}

} // namespace aurex::codegen_c
