#include "aurex/codegen_c/c_emitter.hpp"

#include "aurex/codegen_c/c_type.hpp"
#include "aurex/codegen_c/expr_order.hpp"

#include <unordered_set>
#include <utility>

namespace aurex::codegen_c {

namespace {

[[nodiscard]] std::string binary_op_text(const syntax::BinaryOp op) {
    switch (op) {
    case syntax::BinaryOp::add: return "+";
    case syntax::BinaryOp::sub: return "-";
    case syntax::BinaryOp::mul: return "*";
    case syntax::BinaryOp::div: return "/";
    case syntax::BinaryOp::mod: return "%";
    case syntax::BinaryOp::shl: return "<<";
    case syntax::BinaryOp::shr: return ">>";
    case syntax::BinaryOp::less: return "<";
    case syntax::BinaryOp::less_equal: return "<=";
    case syntax::BinaryOp::greater: return ">";
    case syntax::BinaryOp::greater_equal: return ">=";
    case syntax::BinaryOp::equal: return "==";
    case syntax::BinaryOp::not_equal: return "!=";
    case syntax::BinaryOp::bit_and: return "&";
    case syntax::BinaryOp::bit_xor: return "^";
    case syntax::BinaryOp::bit_or: return "|";
    case syntax::BinaryOp::logical_and: return "&&";
    case syntax::BinaryOp::logical_or: return "||";
    }
    return "?";
}

[[nodiscard]] std::string unary_op_text(const syntax::UnaryOp op) {
    switch (op) {
    case syntax::UnaryOp::logical_not: return "!";
    case syntax::UnaryOp::numeric_negate: return "-";
    case syntax::UnaryOp::bitwise_not: return "~";
    case syntax::UnaryOp::address_of: return "&";
    case syntax::UnaryOp::dereference: return "*";
    }
    return "?";
}

[[nodiscard]] std::unordered_set<base::u32> collect_nested_extern_items(const syntax::AstModule& module) {
    std::unordered_set<base::u32> nested;
    for (const syntax::ItemNode& item : module.items) {
        if (item.kind != syntax::ItemKind::extern_block) {
            continue;
        }
        for (syntax::ItemId id : item.extern_items) {
            if (syntax::is_valid(id)) {
                nested.insert(id.value);
            }
        }
    }
    return nested;
}

} // namespace

CEmitter::CEmitter(const syntax::AstModule& module, const sema::CheckedModule& checked) noexcept
    : module_(module), checked_(checked) {}

base::Result<COutput> CEmitter::emit() {
    static_cast<void>(checked_);
    emit_prelude();
    emit_forward_decls();
    const std::unordered_set<base::u32> nested = collect_nested_extern_items(module_);
    for (base::u32 i = 0; i < module_.items.size(); ++i) {
        if (nested.contains(i)) {
            continue;
        }
        emit_item(module_.items[i]);
    }
    return base::Result<COutput>::ok(COutput {out_.str()});
}

void CEmitter::emit_prelude() {
    out_ << "#include <stdint.h>\n";
    out_ << "#include <stddef.h>\n";
    out_ << "#include <stdbool.h>\n";
    out_ << "#include <stdalign.h>\n\n";
    out_ << "typedef struct aurex_m0_str {\n";
    out_ << "    const uint8_t *data;\n";
    out_ << "    size_t len;\n";
    out_ << "} aurex_m0_str;\n\n";
    out_ << "/* Generated by Aurex M0V0.1.8. */\n\n";
}

void CEmitter::emit_forward_decls() {
    const std::unordered_set<base::u32> nested = collect_nested_extern_items(module_);
    for (base::u32 i = 0; i < module_.items.size(); ++i) {
        if (nested.contains(i)) {
            continue;
        }
        const syntax::ItemNode& item = module_.items[i];
        if (item.kind == syntax::ItemKind::struct_decl) {
            out_ << "typedef struct " << c_type_name(item) << " " << c_type_name(item) << ";\n";
        } else if (item.kind == syntax::ItemKind::opaque_struct_decl) {
            out_ << "typedef struct " << c_type_name(item) << " " << c_type_name(item) << ";\n";
        } else if (item.kind == syntax::ItemKind::extern_block) {
            for (syntax::ItemId id : item.extern_items) {
                const syntax::ItemNode& child = module_.items[id.value];
                if (child.kind == syntax::ItemKind::opaque_struct_decl) {
                    out_ << "typedef struct " << c_type_name(child) << " " << c_type_name(child) << ";\n";
                }
            }
        }
    }
    out_ << "\n";
}

void CEmitter::emit_item(const syntax::ItemNode& item) {
    switch (item.kind) {
    case syntax::ItemKind::const_decl:
        emit_const(item);
        break;
    case syntax::ItemKind::struct_decl:
        emit_struct(item);
        break;
    case syntax::ItemKind::enum_decl:
        emit_enum(item);
        break;
    case syntax::ItemKind::opaque_struct_decl:
        break;
    case syntax::ItemKind::fn_decl:
        if (item.is_extern_c) {
            emit_function_decl(item, true);
        } else if (is_exported_main(item)) {
            emit_main_wrapper(item);
        } else {
            emit_function_decl(item, false);
            out_ << " ";
            emit_block(item.body);
            out_ << "\n";
        }
        break;
    case syntax::ItemKind::extern_block:
        for (syntax::ItemId id : item.extern_items) {
            emit_item(module_.items[id.value]);
        }
        out_ << "\n";
        break;
    }
}

void CEmitter::emit_const(const syntax::ItemNode& item) {
    out_ << "static const " << emit_type(item.const_type, c_name(item))
         << " = " << emit_expr(item.const_value) << ";\n\n";
}

void CEmitter::emit_struct(const syntax::ItemNode& item) {
    out_ << "typedef struct " << c_type_name(item) << " {\n";
    ++indent_;
    for (const syntax::FieldDecl& field : item.fields) {
        write_indent();
        out_ << emit_type(field.type, std::string(field.name)) << ";\n";
    }
    --indent_;
    out_ << "} " << c_type_name(item) << ";\n\n";
}

void CEmitter::emit_enum(const syntax::ItemNode& item) {
    out_ << "typedef " << emit_type(item.enum_base_type) << " " << c_type_name(item) << ";\n";
    out_ << "enum {\n";
    ++indent_;
    for (const syntax::EnumCaseDecl& enum_case : item.enum_cases) {
        write_indent();
        out_ << c_name(item) << "_" << enum_case.name << " = " << enum_case.value_text << ",\n";
    }
    --indent_;
    out_ << "};\n\n";
}

void CEmitter::emit_function_decl(const syntax::ItemNode& item, const bool with_semicolon) {
    emit_function_decl_named(item, c_name(item), with_semicolon);
}

void CEmitter::emit_function_decl_named(const syntax::ItemNode& item, const std::string_view name, const bool with_semicolon) {
    out_ << emit_type(item.return_type) << " " << name << "(";
    for (base::usize i = 0; i < item.params.size(); ++i) {
        if (i != 0) {
            out_ << ", ";
        }
        const syntax::ParamDecl& param = item.params[i];
        out_ << emit_type(param.type, std::string(param.name));
    }
    out_ << ")";
    if (with_semicolon) {
        out_ << ";\n";
    }
}

void CEmitter::emit_main_wrapper(const syntax::ItemNode& item) {
    out_ << "static ";
    emit_function_decl_named(item, "aurex_m0_main", false);
    out_ << " ";
    emit_block(item.body);
    out_ << "\n";
    out_ << "int main(int argc, char **argv) {\n";
    out_ << "    return (int)aurex_m0_main((int32_t)argc, (uint8_t **)argv);\n";
    out_ << "}\n";
}

void CEmitter::emit_block(const syntax::StmtId block_id) {
    out_ << "{\n";
    ++indent_;
    if (syntax::is_valid(block_id) && block_id.value < module_.stmts.size()) {
        const syntax::StmtNode& block = module_.stmts[block_id.value];
        for (syntax::StmtId stmt : block.statements) {
            emit_stmt(stmt);
        }
    }
    --indent_;
    write_indent();
    out_ << "}\n";
}

void CEmitter::emit_stmt(const syntax::StmtId stmt_id) {
    if (!syntax::is_valid(stmt_id) || stmt_id.value >= module_.stmts.size()) {
        return;
    }
    const syntax::StmtNode& stmt = module_.stmts[stmt_id.value];
    switch (stmt.kind) {
    case syntax::StmtKind::let:
    case syntax::StmtKind::var: {
        const std::string init = emit_expr_ordered(stmt.init);
        write_indent();
        out_ << emit_type(stmt.declared_type, std::string(stmt.name)) << " = " << init << ";\n";
        break;
    }
    case syntax::StmtKind::assign: {
        const std::string rhs = emit_expr_ordered(stmt.rhs);
        write_indent();
        out_ << emit_expr(stmt.lhs) << " = " << rhs << ";\n";
        break;
    }
    case syntax::StmtKind::if_: {
        const std::string condition = emit_condition(stmt.condition);
        write_indent();
        out_ << "if " << condition << " ";
        emit_block(stmt.then_block);
        if (syntax::is_valid(stmt.else_block)) {
            write_indent();
            out_ << "else ";
            emit_block(stmt.else_block);
        }
        break;
    }
    case syntax::StmtKind::while_:
        if (expr_contains_call(module_, stmt.condition)) {
            write_indent();
            out_ << "while (true) {\n";
            ++indent_;
            const std::string condition = emit_condition(stmt.condition);
            write_indent();
            out_ << "if (!" << condition << ") {\n";
            ++indent_;
            write_indent();
            out_ << "break;\n";
            --indent_;
            write_indent();
            out_ << "}\n";
            if (syntax::is_valid(stmt.body) && stmt.body.value < module_.stmts.size()) {
                const syntax::StmtNode& block = module_.stmts[stmt.body.value];
                for (syntax::StmtId child : block.statements) {
                    emit_stmt(child);
                }
            }
            --indent_;
            write_indent();
            out_ << "}\n";
        } else {
            write_indent();
            out_ << "while " << emit_condition(stmt.condition) << " ";
            emit_block(stmt.body);
        }
        break;
    case syntax::StmtKind::break_:
        write_indent();
        out_ << "break;\n";
        break;
    case syntax::StmtKind::continue_:
        write_indent();
        out_ << "continue;\n";
        break;
    case syntax::StmtKind::return_:
        if (syntax::is_valid(stmt.return_value)) {
            const std::string value = emit_expr_ordered(stmt.return_value);
            write_indent();
            out_ << "return " << value << ";\n";
        } else {
            write_indent();
            out_ << "return;\n";
        }
        break;
    case syntax::StmtKind::expr:
        if (!emit_call_statement_with_ordering(stmt.init)) {
            write_indent();
            out_ << emit_expr(stmt.init) << ";\n";
        }
        break;
    case syntax::StmtKind::block:
        emit_block(stmt_id);
        break;
    }
}

bool CEmitter::emit_call_statement_with_ordering(const syntax::ExprId expr_id) {
    if (!syntax::is_valid(expr_id) || expr_id.value >= module_.exprs.size()) {
        return false;
    }
    const syntax::ExprNode& expr = module_.exprs[expr_id.value];
    if (expr.kind != syntax::ExprKind::call) {
        return false;
    }

    std::vector<std::string> args;
    args.reserve(expr.args.size());
    bool lowered = false;
    for (base::usize i = 0; i < expr.args.size(); ++i) {
        const syntax::ExprId arg = expr.args[i];
        if (expr_contains_call(module_, arg)) {
            const std::string temp_name = lower_expr_to_temp(arg);
            if (temp_name.empty()) {
                args.push_back(emit_expr(arg));
            } else {
                args.push_back(temp_name);
                lowered = true;
            }
        } else {
            args.push_back(emit_expr(arg));
        }
    }
    if (!lowered) {
        return false;
    }

    write_indent();
    out_ << emit_callee(expr.callee) << "(";
    for (base::usize i = 0; i < args.size(); ++i) {
        if (i != 0) {
            out_ << ", ";
        }
        out_ << args[i];
    }
    out_ << ");\n";
    return true;
}

std::string CEmitter::emit_expr_ordered(const syntax::ExprId expr_id) {
    if (!expr_contains_call(module_, expr_id)) {
        return emit_expr(expr_id);
    }
    const std::string temp_name = lower_expr_to_temp(expr_id);
    return temp_name.empty() ? emit_expr(expr_id) : temp_name;
}

std::string CEmitter::lower_expr_to_temp(const syntax::ExprId expr_id) {
    if (!syntax::is_valid(expr_id) || expr_id.value >= module_.exprs.size()) {
        return {};
    }

    const sema::TypeHandle type = expr_id.value < checked_.expr_types.size() ? checked_.expr_types[expr_id.value] : sema::invalid_type_handle;
    const syntax::ExprNode& expr = module_.exprs[expr_id.value];
    if (expr.kind == syntax::ExprKind::binary &&
        (expr.binary_op == syntax::BinaryOp::logical_and || expr.binary_op == syntax::BinaryOp::logical_or)) {
        return lower_logical_expr_to_temp(expr_id);
    }

    std::string value;
    if (expr.kind == syntax::ExprKind::binary) {
        const std::string lhs = lower_child_if_needed(expr.binary_lhs);
        const std::string rhs = lower_child_if_needed(expr.binary_rhs);
        value = "(" + lhs +
            " " + binary_op_text(expr.binary_op) + " " +
            rhs + ")";
    } else if (expr.kind == syntax::ExprKind::call) {
        const std::vector<syntax::ExprId>& source_args = expr.args;
        std::vector<std::string> args;
        args.reserve(source_args.size());
        for (const syntax::ExprId arg : source_args) {
            args.push_back(lower_child_if_needed(arg));
        }
        value = emit_callee(expr.callee) + "(";
        for (base::usize i = 0; i < args.size(); ++i) {
            if (i != 0) {
                value += ", ";
            }
            value += args[i];
        }
        value += ")";
    } else if (expr.kind == syntax::ExprKind::unary) {
        value = "(" + unary_op_text(expr.unary_op) + lower_child_if_needed(expr.unary_operand) + ")";
    } else if (expr.kind == syntax::ExprKind::field) {
        value = lower_child_if_needed(expr.object) + (expr_has_pointer_type(expr.object) ? "->" : ".") + std::string(expr.field_name);
    } else if (expr.kind == syntax::ExprKind::index) {
        const std::string object = lower_child_if_needed(expr.object);
        const std::string index = lower_child_if_needed(expr.index);
        value = object + "[" + index + "]";
    } else if (expr.kind == syntax::ExprKind::struct_literal) {
        value = "(" + checked_.types.c_name(type) + "){";
        for (base::usize i = 0; i < expr.field_inits.size(); ++i) {
            if (i != 0) {
                value += ", ";
            }
            value += "." + std::string(expr.field_inits[i].name) + " = " + lower_child_if_needed(expr.field_inits[i].value);
        }
        value += "}";
    } else if (expr.kind == syntax::ExprKind::cast ||
               expr.kind == syntax::ExprKind::ptr_cast ||
               expr.kind == syntax::ExprKind::bit_cast) {
        value = "((" + emit_type(expr.cast_type) + ")(" + lower_child_if_needed(expr.cast_expr) + "))";
    } else if (expr.kind == syntax::ExprKind::ptr_addr) {
        value = "((size_t)(uintptr_t)(" + lower_child_if_needed(expr.cast_expr) + "))";
    } else if (expr.kind == syntax::ExprKind::ptr_from_addr) {
        value = "((" + emit_type(expr.cast_type) + ")(uintptr_t)(" + lower_child_if_needed(expr.cast_expr) + "))";
    } else {
        value = emit_expr(expr_id);
    }

    return declare_temp(type, value);
}

std::string CEmitter::lower_logical_expr_to_temp(const syntax::ExprId expr_id) {
    if (!syntax::is_valid(expr_id) || expr_id.value >= module_.exprs.size()) {
        return {};
    }
    const syntax::ExprNode& expr = module_.exprs[expr_id.value];
    if (expr.kind != syntax::ExprKind::binary) {
        return lower_expr_to_temp(expr_id);
    }

    const sema::TypeHandle bool_type = expr_id.value < checked_.expr_types.size()
        ? checked_.expr_types[expr_id.value]
        : sema::invalid_type_handle;
    const std::string temp_name = "__m0_tmp" + std::to_string(temp_index_++);
    write_indent();
    out_ << format_c_type(checked_.types, bool_type, temp_name) << " = false;\n";

    const std::string lhs = lower_child_if_needed(expr.binary_lhs);
    write_indent();
    if (expr.binary_op == syntax::BinaryOp::logical_and) {
        out_ << "if (" << lhs << ") ";
        out_ << "{\n";
        ++indent_;
        const std::string rhs = lower_child_if_needed(expr.binary_rhs);
        write_indent();
        out_ << temp_name << " = " << rhs << ";\n";
        --indent_;
        write_indent();
        out_ << "}\n";
    } else {
        out_ << "if (" << lhs << ") ";
        out_ << "{\n";
        ++indent_;
        write_indent();
        out_ << temp_name << " = true;\n";
        --indent_;
        write_indent();
        out_ << "} else {\n";
        ++indent_;
        const std::string rhs = lower_child_if_needed(expr.binary_rhs);
        write_indent();
        out_ << temp_name << " = " << rhs << ";\n";
        --indent_;
        write_indent();
        out_ << "}\n";
    }
    return temp_name;
}

std::string CEmitter::lower_child_if_needed(const syntax::ExprId expr_id) {
    if (!expr_contains_call(module_, expr_id)) {
        return emit_expr(expr_id);
    }
    const std::string temp_name = lower_expr_to_temp(expr_id);
    return temp_name.empty() ? emit_expr(expr_id) : temp_name;
}

std::string CEmitter::emit_expr(syntax::ExprId expr_id) {
    if (!syntax::is_valid(expr_id) || expr_id.value >= module_.exprs.size()) {
        return "/*invalid*/0";
    }
    const syntax::ExprNode& expr = module_.exprs[expr_id.value];
    switch (expr.kind) {
    case syntax::ExprKind::integer_literal:
    case syntax::ExprKind::bool_literal:
        return std::string(expr.text);
    case syntax::ExprKind::null_literal:
        return "NULL";
    case syntax::ExprKind::string_literal:
        return "(aurex_m0_str){ .data = (const uint8_t *)" + escape_c_string(expr.text) +
            ", .len = " + std::to_string(expr.text.size() >= 2 ? expr.text.size() - 2 : 0) + " }";
    case syntax::ExprKind::c_string_literal:
        return "(const uint8_t *)" + escape_c_string(expr.text.substr(1));
    case syntax::ExprKind::byte_literal:
        return std::string(expr.text.substr(1));
    case syntax::ExprKind::name:
        return emit_name(expr_id);
    case syntax::ExprKind::unary:
        return "(" + unary_op_text(expr.unary_op) + emit_expr(expr.unary_operand) + ")";
    case syntax::ExprKind::binary:
        return "(" + emit_expr(expr.binary_lhs) + " " + binary_op_text(expr.binary_op) + " " + emit_expr(expr.binary_rhs) + ")";
    case syntax::ExprKind::call: {
        std::string result = emit_callee(expr.callee);
        result += "(";
        for (base::usize i = 0; i < expr.args.size(); ++i) {
            if (i != 0) {
                result += ", ";
            }
            result += emit_expr(expr.args[i]);
        }
        result += ")";
        return result;
    }
    case syntax::ExprKind::field:
        return emit_expr(expr.object) + (expr_has_pointer_type(expr.object) ? "->" : ".") + std::string(expr.field_name);
    case syntax::ExprKind::index:
        return emit_expr(expr.object) + "[" + emit_expr(expr.index) + "]";
    case syntax::ExprKind::struct_literal: {
        std::string result = "(" + checked_.types.c_name(checked_.expr_types[expr_id.value]) + "){";
        for (base::usize i = 0; i < expr.field_inits.size(); ++i) {
            if (i != 0) {
                result += ", ";
            }
            result += "." + std::string(expr.field_inits[i].name) + " = " + emit_expr(expr.field_inits[i].value);
        }
        result += "}";
        return result;
    }
    case syntax::ExprKind::cast:
    case syntax::ExprKind::ptr_cast:
    case syntax::ExprKind::bit_cast:
        return "((" + emit_type(expr.cast_type) + ")(" + emit_expr(expr.cast_expr) + "))";
    case syntax::ExprKind::size_of:
        return "((size_t)sizeof(" + emit_type(expr.cast_type) + "))";
    case syntax::ExprKind::align_of:
        return "((size_t)alignof(" + emit_type(expr.cast_type) + "))";
    case syntax::ExprKind::ptr_addr:
        return "((size_t)(uintptr_t)(" + emit_expr(expr.cast_expr) + "))";
    case syntax::ExprKind::ptr_from_addr:
        return "((" + emit_type(expr.cast_type) + ")(uintptr_t)(" + emit_expr(expr.cast_expr) + "))";
    case syntax::ExprKind::invalid:
        return "/*invalid*/0";
    }
    return "/*unknown*/0";
}

std::string CEmitter::emit_condition(const syntax::ExprId expr_id) {
    const std::string value = emit_expr_ordered(expr_id);
    if (!value.empty() && value.front() == '(' && value.back() == ')') {
        return value;
    }
    return "(" + value + ")";
}

std::string CEmitter::emit_type(syntax::TypeId type_id, std::string declarator) {
    return format_c_type(module_, checked_, type_id, std::move(declarator));
}

std::string CEmitter::emit_callee(const syntax::ExprId callee) const {
    if (!syntax::is_valid(callee) || callee.value >= module_.exprs.size()) {
        return "/*invalid_callee*/";
    }
    const syntax::ExprNode& expr = module_.exprs[callee.value];
    if (expr.kind != syntax::ExprKind::name) {
        return std::string(expr.text);
    }
    return emit_name(callee);
}

std::string CEmitter::emit_name(const syntax::ExprId expr) const {
    if (!syntax::is_valid(expr) || expr.value >= module_.exprs.size()) {
        return "/*invalid_name*/";
    }
    if (expr.value < checked_.expr_c_names.size() && !checked_.expr_c_names[expr.value].empty()) {
        return checked_.expr_c_names[expr.value];
    }
    return std::string(module_.exprs[expr.value].text);
}

sema::TypeHandle CEmitter::type_handle(const syntax::TypeId type) const noexcept {
    if (!syntax::is_valid(type) || type.value >= checked_.syntax_type_handles.size()) {
        return sema::invalid_type_handle;
    }
    return checked_.syntax_type_handles[type.value];
}

std::string CEmitter::c_name(const syntax::ItemNode& item) const {
    const auto item_begin = module_.items.data();
    const auto item_end = item_begin + module_.items.size();
    if (&item < item_begin || &item >= item_end) {
        return std::string(item.name);
    }
    const base::usize item_index = static_cast<base::usize>(&item - item_begin);
    if (item_index < checked_.item_c_names.size() && !checked_.item_c_names[item_index].empty()) {
        return checked_.item_c_names[item_index];
    }
    return std::string(item.name);
}

std::string CEmitter::c_type_name(const syntax::ItemNode& item) const {
    if (item.kind != syntax::ItemKind::struct_decl &&
        item.kind != syntax::ItemKind::enum_decl &&
        item.kind != syntax::ItemKind::opaque_struct_decl) {
        return std::string(item.name);
    }
    const auto item_begin = module_.items.data();
    const auto item_end = item_begin + module_.items.size();
    if (&item < item_begin || &item >= item_end) {
        return std::string(item.name);
    }
    const base::usize item_index = static_cast<base::usize>(&item - item_begin);
    if (item_index >= module_.item_modules.size()) {
        return std::string(item.name);
    }
    const syntax::ModuleId item_module = module_.item_modules[item_index];
    for (const auto& entry : checked_.structs) {
        const sema::StructInfo& info = entry.second;
        if (info.module.value == item_module.value && info.name == item.name) {
            return info.c_name;
        }
    }
    if (item.kind == syntax::ItemKind::enum_decl) {
        const base::usize item_index = static_cast<base::usize>(&item - item_begin);
        if (item_index < checked_.item_c_names.size() && !checked_.item_c_names[item_index].empty()) {
            return checked_.item_c_names[item_index];
        }
    }
    return std::string(item.name);
}

std::string CEmitter::escape_c_string(const std::string_view literal) const {
    return std::string(literal);
}

bool CEmitter::is_exported_main(const syntax::ItemNode& item) const noexcept {
    return item.kind == syntax::ItemKind::fn_decl && item.is_export_c && item.name == "main";
}

bool CEmitter::expr_has_pointer_type(const syntax::ExprId expr) const noexcept {
    if (!syntax::is_valid(expr) || expr.value >= checked_.expr_types.size()) {
        return false;
    }
    const sema::TypeHandle type = checked_.expr_types[expr.value];
    return sema::is_valid(type) && checked_.types.is_pointer(type);
}

std::string CEmitter::declare_temp(const sema::TypeHandle type, std::string value) {
    if (!sema::is_valid(type)) {
        return {};
    }
    const std::string temp_name = "__m0_tmp" + std::to_string(temp_index_++);
    write_indent();
    out_ << format_c_type(checked_.types, type, temp_name) << " = " << value << ";\n";
    return temp_name;
}

void CEmitter::write_indent() {
    for (int i = 0; i < indent_; ++i) {
        out_ << "    ";
    }
}

} // namespace aurex::codegen_c
