// Nex build tool for M0 projects. C++20, standalone, zero external deps.
//
// Usage:  nex                  # reads ./Nexfile, writes ./axbuild.mk
//         nex <Nexfile>       # specify config path
//         nex -f <Nexfile>    # same
//         make -f axbuild.mk   # then build

#include "scanner.hpp"

#include <algorithm>
#include <cctype>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <optional>
#include <ostream>
#include <string>
#include <string_view>
#include <vector>

namespace fs = std::filesystem;

namespace nex {
namespace {

// ── Trim ──────────────────────────────────────────────────────────────────

std::string_view trim(std::string_view s) {
    while (!s.empty() && std::isspace(static_cast<unsigned char>(s.front()))) s.remove_prefix(1);
    while (!s.empty() && std::isspace(static_cast<unsigned char>(s.back()))) s.remove_suffix(1);
    return s;
}

// ── Config ───────────────────────────────────────────────────────────────
// Nexfile parser. Format: key = value  (one per line, repeatable keys)
// Comments start with #. Blank lines are ignored.

struct Config {
    std::string         project;
    std::string         entry;
    std::string         output;
    std::vector<std::string> imports;
    std::vector<std::string> links;
    std::string         m0_flags;
    std::string         c_flags;
};

[[nodiscard]] std::optional<Config> read_config(const fs::path& path) {
    std::ifstream in(path);
    if (!in) return std::nullopt;

    Config cfg;
    int line_no = 0;
    for (std::string line; std::getline(in, line); ) {
        ++line_no;

        // strip comment
        auto comment = line.find('#');
        if (comment != std::string::npos) line.resize(comment);

        auto trimmed = trim(line);
        if (trimmed.empty()) continue;

        auto eq = trimmed.find('=');
        if (eq == std::string_view::npos) {
            std::cerr << "nex: Nexfile:" << line_no << ": missing '='\n";
            return std::nullopt;
        }

        auto key = trim(trimmed.substr(0, eq));
        auto val = trim(trimmed.substr(eq + 1));

        if (key == "project")      cfg.project   = std::string(val);
        else if (key == "entry")   cfg.entry     = std::string(val);
        else if (key == "output")  cfg.output    = std::string(val);
        else if (key == "import")  cfg.imports.push_back(std::string(val));
        else if (key == "link")    cfg.links.push_back(std::string(val));
        else if (key == "m0_flags") cfg.m0_flags = std::string(val);
        else if (key == "c_flags")  cfg.c_flags  = std::string(val);
        else {
            std::cerr << "nex: Nexfile:" << line_no << ": unknown key '" << key << "'\n";
            return std::nullopt;
        }
    }

    return cfg;
}

// ── Helpers ───────────────────────────────────────────────────────────────

std::string basename_no_ext(const fs::path& path) {
    auto name = path.filename().string();
    if (name.ends_with(".ax")) name.resize(name.size() - 3);
    return name;
}

[[nodiscard]] bool file_exists(const fs::path& p) {
    std::error_code ec;
    return fs::exists(p, ec) && !ec;
}

[[nodiscard]] std::optional<std::string> read_file(const fs::path& p) {
    std::ifstream in(p, std::ios::binary);
    if (!in) return std::nullopt;
    std::ostringstream buf;
    buf << in.rdbuf();
    return buf.str();
}

// ── Makefile emission ─────────────────────────────────────────────────────

void emit_makefile(std::ostream& out, const Config& cfg) {
    auto entry = fs::path(cfg.entry);
    std::string target = cfg.output.empty() ? basename_no_ext(entry) : cfg.output;

    out << "# Generated by Nex\n";
    out << "#   entry: " << cfg.entry << '\n';
    if (!cfg.project.empty()) out << "#   project: " << cfg.project << '\n';
    out << '\n';

    out << "M0C    ?= m0c\n";
    out << "CC     ?= cc\n";
    out << "BUILD  ?= axbuild\n";
    out << '\n';

    out << "M0FLAGS =";
    for (auto& imp : cfg.imports) out << " -I " << imp;
    if (!cfg.m0_flags.empty()) out << ' ' << cfg.m0_flags;
    out << '\n';

    out << "CFLAGS  =" << (cfg.c_flags.empty() ? "" : " " + cfg.c_flags) << '\n';

    out << "LDFLAGS =";
    for (auto& l : cfg.links) out << ' ' << l;
    out << '\n';
    out << '\n';

    // ── all ──
    out << ".PHONY: all\n";
    out << "all: $(BUILD)/" << target << '\n';
    out << '\n';

    // ── link ──
    out << "$(BUILD)/" << target << ": $(BUILD)/" << target << ".c";
    for (auto& l : cfg.links) {
        out << ' ' << l;  // source dependency
    }
    out << '\n';
    out << "\t$(CC) $(BUILD)/" << target << ".c $(LDFLAGS) $(CFLAGS) -o $(BUILD)/" << target << '\n';
    out << '\n';

    // ── compile ──
    out << "$(BUILD)/" << target << ".c: " << cfg.entry;
    // Also depend on all linked C sources
    for (auto& l : cfg.links) out << ' ' << l;
    out << '\n';
    out << "\t@mkdir -p $(BUILD)\n";
    out << "\t$(M0C) $(M0FLAGS) " << cfg.entry << " -o $(BUILD)/" << target << ".c\n";
    out << '\n';

    // ── clean ──
    out << ".PHONY: clean\n";
    out << "clean:\n";
    out << "\trm -rf $(BUILD)\n";
}

// ── Validation ────────────────────────────────────────────────────────────

bool validate_config(const Config& cfg) {
    if (cfg.entry.empty()) {
        std::cerr << "nex: Nexfile: 'entry' is required\n";
        return false;
    }
    if (!file_exists(cfg.entry)) {
        std::cerr << "nex: entry file not found: " << cfg.entry << '\n';
        return false;
    }
    for (auto& imp : cfg.imports) {
        if (!fs::is_directory(imp)) {
            std::cerr << "nex: import path is not a directory: " << imp << '\n';
            return false;
        }
    }
    return true;
}

} // namespace
} // namespace nex

// ── CLI ───────────────────────────────────────────────────────────────────

int main(int argc, char** argv) {
    fs::path config_path = "Nexfile";
    fs::path output_path = "axbuild.mk";

    for (int i = 1; i < argc; ++i) {
        std::string_view arg(argv[i]);
        if (arg == "-h" || arg == "--help") {
            std::cout
                << "Nex — build tool for M0 projects\n"
                << "usage: nex [Nexfile] | -o <output>\n"
                << "       defaults to ./Nexfile, outputs ./axbuild.mk\n"
                << "       then: make -f axbuild.mk\n";
            return 0;
        }
        if (arg == "-o" && i + 1 < argc) {
            output_path = argv[++i];
        } else if (arg == "-f" && i + 1 < argc) {
            config_path = argv[++i];
        } else if (!arg.empty() && arg.front() != '-') {
            config_path = arg;
        } else {
            std::cerr << "nex: unknown flag: " << arg << '\n';
            return 2;
        }
    }

    auto cfg = read_config(config_path);
    if (!cfg) {
        std::cerr << "nex: failed to read " << config_path.string() << '\n';
        return 1;
    }

    if (!validate_config(*cfg)) return 1;

    // Print scan summary
    auto source_text = read_file(cfg->entry);
    if (source_text) {
        auto info = scan_source(*source_text);
        std::cout << "nex: module   " << info.module_name << '\n';
        for (auto& imp : info.imports) {
            std::cout << "nex:   import " << imp << '\n';
        }
    }

    // Write Makefile
    std::ofstream out(output_path, std::ios::binary);
    if (!out) {
        std::cerr << "nex: failed to open " << output_path.string() << '\n';
        return 1;
    }
    emit_makefile(out, *cfg);
    out.close();

    if (!out) {
        std::cerr << "nex: write error\n";
        return 1;
    }

    std::cout << "nex: generated " << output_path.string() << '\n';
    return 0;
}

} // namespace nex
