#pragma once

#include "aurex/base/source.hpp"

#include <string_view>

namespace aurex::syntax {

enum class TokenKind {
    eof,
    invalid,
    identifier,
    integer_literal,
    string_literal,
    c_string_literal,
    byte_literal,
    kw_module,
    kw_import,
    kw_as,
    kw_pub,
    kw_priv,
    kw_extern,
    kw_export,
    kw_c,
    kw_fn,
    kw_struct,
    kw_opaque,
    kw_enum,
    kw_const,
    kw_type,
    kw_impl,
    kw_match,
    kw_let,
    kw_var,
    kw_if,
    kw_else,
    kw_for,
    kw_while,
    kw_break,
    kw_continue,
    kw_defer,
    kw_return,
    kw_noncopy,
    kw_move,
    kw_true,
    kw_false,
    kw_null,
    kw_void,
    kw_bool,
    kw_i8,
    kw_u8,
    kw_i16,
    kw_u16,
    kw_i32,
    kw_u32,
    kw_i64,
    kw_u64,
    kw_isize,
    kw_usize,
    kw_f32,
    kw_f64,
    kw_str,
    kw_mut,
    kw_cast,
    kw_ptr_cast,
    kw_bit_cast,
    kw_size_of,
    kw_align_of,
    kw_ptr_addr,
    kw_ptr_from_addr,
    kw_str_data,
    kw_str_byte_len,
    kw_str_from_bytes_unchecked,
    l_paren,
    r_paren,
    l_brace,
    r_brace,
    l_bracket,
    r_bracket,
    comma,
    dot,
    ellipsis,
    semicolon,
    colon,
    colon_colon,
    arrow,
    fat_arrow,
    plus,
    minus,
    star,
    slash,
    percent,
    amp,
    pipe,
    caret,
    tilde,
    bang,
    equal,
    equal_equal,
    bang_equal,
    less,
    less_equal,
    greater,
    greater_equal,
    less_less,
    greater_greater,
    amp_amp,
    pipe_pipe,
    question,
    at,
};

struct Token {
    TokenKind kind = TokenKind::invalid;
    base::SourceRange range {};
    std::string_view text;
};

[[nodiscard]] std::string_view token_kind_name(TokenKind kind) noexcept;

} // namespace aurex::syntax
