add_library(aurex_query
    src/infrastructure/query/stable_hash.cpp
    src/infrastructure/query/stable_identity.cpp
    src/infrastructure/query/query_key.cpp
    src/infrastructure/query/query_graph.cpp
    src/infrastructure/query/query_interner.cpp
    src/infrastructure/query/query_provider_set.cpp
    src/infrastructure/query/query_executor.cpp
    src/infrastructure/query/query_replay.cpp
    src/infrastructure/query/stable_key_decoder.cpp
    src/infrastructure/query/query_edge_verifier.cpp
    src/infrastructure/query/query_result.cpp
    src/infrastructure/query/query_reuse.cpp
    src/infrastructure/query/cleanup_marker_facts.cpp
    src/infrastructure/query/dyn_advanced_design_gate.cpp
    src/infrastructure/query/dyn_abi_facts.cpp
    src/infrastructure/query/project_graph_query.cpp
    src/infrastructure/query/source_file_query.cpp
    src/infrastructure/query/diagnostics_query.cpp
    src/infrastructure/query/module_graph_query.cpp
    src/infrastructure/query/module_part_query.cpp
    src/infrastructure/query/module_exports_query.cpp
    src/infrastructure/query/item_list_query.cpp
    src/infrastructure/query/item_signature_query.cpp
    src/infrastructure/query/generic_template_signature_query.cpp
    src/infrastructure/query/generic_instance_signature_query.cpp
    src/infrastructure/query/generic_instance_body_query.cpp
    src/infrastructure/query/lower_function_ir_query.cpp
    src/infrastructure/query/function_body_syntax_query.cpp
    src/infrastructure/query/type_check_body_query.cpp
    src/infrastructure/query/query_context.cpp
    src/infrastructure/query/canonical_type_key.cpp
    src/infrastructure/query/generic_instance_key.cpp
    src/infrastructure/query/trait_object_key.cpp
)
target_link_libraries(aurex_query PUBLIC aurex_base)
target_include_directories(aurex_query PUBLIC include)
