add_library(aurex_sema
    src/frontend/sema/types/type.cpp
    src/frontend/sema/resources/resource_semantics.cpp
    src/frontend/sema/resources/drop_glue.cpp
    src/frontend/sema/types/canonical_type_builder.cpp
    src/frontend/sema/symbols/symbol.cpp
    src/frontend/sema/symbols/identifier.cpp
    src/frontend/sema/symbols/function.cpp
    src/frontend/sema/symbols/function_registry.cpp
    src/frontend/sema/internal/declarations/sources/sema_generic_analyzer.cpp
    src/frontend/sema/generics/generic_instance_identity.cpp
    src/frontend/sema/checked/checked_module.cpp
    src/frontend/sema/internal/core/sources/name_resolution.cpp
    src/frontend/sema/internal/borrow/sources/contract.cpp
    src/frontend/sema/internal/borrow/sources/summary.cpp
    src/frontend/sema/internal/lifetime/sources/facts.cpp
    src/frontend/sema/internal/lifetime/sources/collect.cpp
    src/frontend/sema/internal/lifetime/sources/solve.cpp
    src/frontend/sema/internal/lifetime/sources/enforce.cpp
    src/frontend/sema/internal/dropck/sources/facts.cpp
    src/frontend/sema/internal/dropck/sources/collect.cpp
    src/frontend/sema/internal/dropck/sources/solve.cpp
    src/frontend/sema/internal/dropck/sources/enforce.cpp
    src/frontend/sema/internal/expressions/sources/sema_builtin_expression_analyzer.cpp
    src/frontend/sema/internal/borrow/sources/flow_graph.cpp
    src/frontend/sema/internal/borrow/sources/loan_checker.cpp
    src/frontend/sema/internal/place/sources/move_analysis.cpp
    src/frontend/sema/internal/expressions/sources/sema_control_expression_analyzer.cpp
    src/frontend/sema/internal/declarations/sources/sema_declaration_analyzer.cpp
    src/frontend/sema/internal/diagnostics/sources/sema_diagnostics.cpp
    src/frontend/sema/internal/expressions/sources/sema_expression_analyzer.cpp
    src/frontend/sema/internal/lookup/sources/sema_lookup_resolver.cpp
    src/frontend/sema/internal/lookup/sources/sema_lookup_indexer.cpp
    src/frontend/sema/internal/expressions/sources/sema_operator_expression_analyzer.cpp
    src/frontend/sema/internal/pipeline/sources/analysis_pipeline.cpp
    src/frontend/sema/internal/expressions/sources/sema_projection_aggregate_expression_analyzer.cpp
    src/frontend/sema/internal/services/sources/sema_services.cpp
    src/frontend/sema/internal/core/sources/sema_side_tables.cpp
    src/frontend/sema/internal/expressions/sources/sema_statement_analyzer.cpp
    src/frontend/sema/internal/traits/sources/sema_trait_analyzer.cpp
    src/frontend/sema/internal/services/sources/sema_type_services.cpp
    src/frontend/sema/internal/patterns/sources/sema_pattern_match_analyzer.cpp
    src/frontend/sema/facade/sema_call.cpp
    src/frontend/sema/facade/sema_expr.cpp
    src/frontend/sema/facade/sema_lookup.cpp
    src/frontend/sema/facade/sema_record.cpp
    src/frontend/sema/facade/sema_types.cpp
    src/frontend/sema/facade/sema_facade.cpp
    src/frontend/sema/facade/sema.cpp
)
target_link_libraries(aurex_sema PUBLIC aurex_base aurex_syntax aurex_query)
target_include_directories(aurex_sema
    PUBLIC include
    PRIVATE src
)
